/* Café Life presentation. Rules live in engine.js; every action uses the same resolver. */
(function(){'use strict';
const E=window.CafeEngine,C=window.CafeContent,S=window.CafeStrings,A=window.CafeAudio;
const KEY='cafelife_daily_6',BACKUP=KEY+'_backup',ARCHIVE=KEY+'_before_restore',OLD='cafelife_mgmt_2';
const app=document.getElementById('app');
const P=window.CafeSaveStore({getItem:key=>localStorage.getItem(key),setItem:(key,value)=>localStorage.setItem(key,value)},E);
let importDraft='',snapshotId=null,exportSnapshot=null,nativeCounter=0;const nativePending=new Map();
let G=null,lang='en',page='cafe',panel='menu',notice='',saveError=false,selectedRecipe=null,storyId=null,result=null,memoryId=null,selectedHeir=null,exportOriginal=false,exportBackup=false,draft={},form={base:'milk',flavour:'saffron',temperature:'hot',name:''},lastRecipe=null;
const esc=x=>String(x==null?'':x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function t(key,values){const item=S[key];let text=item?item[lang==='ar'?1:0]:key;for(const [k,v]of Object.entries(values||{}))text=text.replaceAll('{'+k+'}',String(v));return text;}
const L=value=>typeof value==='string'?value:value?(value[lang]||value.en||''):'';
const num=n=>new Intl.NumberFormat(lang==='ar'?'ar-AE':'en-GB',{maximumFractionDigits:2}).format(Number(n)||0);
const cash=n=>num(n)+' '+t('aed');
function date(value,short){try{return E.parseDate?E.parseDate(value).toLocaleDateString(lang==='ar'?'ar-AE':'en-GB',{timeZone:'UTC',day:'numeric',month:short?'short':'long',year:'numeric',...(!short?{weekday:'long'}:{})}):new Date(value+'T12:00:00Z').toLocaleDateString(lang==='ar'?'ar-AE':'en-GB',{timeZone:'UTC',day:'numeric',month:short?'short':'long',year:'numeric',...(!short?{weekday:'long'}:{})});}catch(_){return value;}}
const art=name=>(window.ART_DATA&&window.ART_DATA[name])||'../art/sprites/'+name+'.png';
const brand=name=>(window.BRAND_DATA&&window.BRAND_DATA[name])||(name==='icon'?'../native/assets/icon.png':'../art/brand/logo.png');
const img=(name,cls='',alt='')=>`<img src="${art(name)}" class="${cls}" alt="${esc(alt)}" draggable="false">`;
const paths={arrow:'M5 12h14m-6-6 6 6-6 6',back:'M19 12H5m6-6-6 6 6 6',check:'m5 12 4 4 10-10',plus:'M12 5v14M5 12h14',cafe:'M3 10h18M5 10v11h14V10M3 10l2-7h14l2 7M9 21v-7h6v7',menu:'M4 5h12v9a6 6 0 0 1-12 0V5Zm12 1h2a3 3 0 0 1 0 6h-2M2 22h17',people:'M16 21v-3a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v3M9 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8M22 21v-3a4 4 0 0 0-3-4M16 2a4 4 0 0 1 0 8',book:'M12 5C8 2 4 3 2 4v16c4-2 7-1 10 1 3-2 6-3 10-1V4c-3-1-6-2-10 1Zm0 0v16',settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1 1-3Zm3 6a3 3 0 1 0 0 6 3 3 0 0 0 0-6',room:'M5 12V7a4 4 0 0 1 4-4h6a4 4 0 0 1 4 4v5M3 10v8h18v-8M6 18v3m12-3v3M3 14h18',spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3 3-7',heart:'M20 4a5 5 0 0 0-8 1 5 5 0 0 0-8-1c-5 5 1 11 8 17 7-6 13-12 8-17Z',sun:'M12 3v2m0 14v2M3 12h2m14 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',coin:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0M12 6v12m3-10h-4a2 2 0 0 0 0 4h2a2 2 0 0 1 0 4H9',image:'M3 3h18v18H3V3Zm0 13 6-6 12 11M15 7h.01',clock:'M12 8v5l3 2M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',leaf:'M20 3C8 1 2 9 7 17s15 1 13-14ZM4 21 16 8',save:'M5 3h12l4 4v14H3V3h2Zm2 0v6h10V3M7 21v-7h10v7',volume:'m3 9 5 0 5-5v16l-5-5H3V9Zm14-1a7 7 0 0 1 0 8m3-11a11 11 0 0 1 0 14',close:'m6 6 12 12M6 18 18 6',archive:'M3 3h18v5H3V3Zm2 5v13h14V8M9 12h6',flag:'M5 22V3c5-4 9 4 15 0v11c-6 4-10-4-15 0'};
const icon=name=>`<svg viewBox="0 0 24 24" class="${name==='arrow'||name==='back'?'arrow':''}" aria-hidden="true"><path d="${paths[name]||paths.spark}"/></svg>`;
const button=(action,label,cls='primary',attrs='',ic='arrow')=>`<button type="button" class="${cls}" data-action="${action}" ${attrs}><span class="grow">${label}</span>${ic?icon(ic):''}</button>`;
const go=(target,label,cls='text-button wide',extra='',ic='arrow')=>button('go',label,cls,`data-page="${target}" ${extra}`,ic);
const back=(target='cafe')=>go(target,esc(t('back')),'text-button back','', 'back');
const find=(key,id)=>C[key].find(x=>x.id===id);
const recipe=id=>E.recipe(G,id);
const person=id=>find('characters',id);
const allRecipes=()=>E.allRecipes(G);
const stories=()=>E.availableStories(G);
function get(key){try{return localStorage.getItem(key);}catch(_){return null;}}
function persist(){if(!G)return;try{P.save(G);saveError=false;}catch(_){saveError=true;}}
function load(){try{const found=P.load();if(found){G=found.state;lang=G.lang;if(found.recovered)notice=t('saveRecovered');}}catch(_){saveError=true;}}
function send(message){try{window.ReactNativeWebView?.postMessage(JSON.stringify(message));}catch(_){}}
function announce(message){document.getElementById('announcer').textContent=message;}
function effects(items){const types=items.map(x=>x.type);if(types.includes('brief')||types.includes('story')||types.includes('ambition')||types.includes('succession')){A?.play('success');celebrate();}else if(types.includes('close'))A?.play('coins');else if(types.includes('open'))A?.play('open');else if(types.includes('serve')){A?.play('pour');A?.play('serve');const el=document.querySelector('.service-card');if(el&&!G.settings.reducedMotion){el.classList.add('serve-flash');}}else if(types.includes('purchase')||types.includes('recipe'))A?.play('success');else A?.play('tap');}
function dispatch(action){if(!G)return{error:'NO_GAME'};const r=E.dispatch(G,action);if(r.error){notice=t(r.error==='NOT_ENOUGH_CASH'?'notEnough':r.error==='RECIPE_EXISTS'?'recipeExists':'actionError');A?.play('error');render();announce(notice);return r;}G=r.state;lang=G.lang;const rewards=r.effects.filter(x=>x.type==='ambition');if(rewards.length)notice=rewards.map(x=>t('ambitionReward',{name:L(find('ambitions',x.id)?.name),cash:cash(x.amount)})).join(' · ');persist();render();effects(r.effects);return r;}
function start(options){G=E.newGame(Object.assign({name:t('defaultCafe'),owner:t('defaultOwner'),lang,origin:'family'},options));lang=G.lang;page='cafe';notice='';persist();render();A?.configure(G.settings);A?.play('open');return G;}
function celebrate(){if(G?.settings.reducedMotion||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const holder=document.createElement('div');holder.className='confetti';holder.setAttribute('aria-hidden','true');holder.innerHTML=Array.from({length:16},(_,i)=>`<i style="--x:${(i*37)%100}%;--d:${(i%4)*.05}s;--c:${['#dcb869','#7fa995','#c67a57'][i%3]}"></i>`).join('');app.appendChild(holder);setTimeout(()=>holder.remove(),1400);}
function header(){return `<header class="shell-header"><img src="${brand('icon')}" class="brand-mark" alt=""><div class="identity"><div class="eyebrow">${t('brand')}</div><div class="cafe-name" dir="auto">${esc(G.cafeName)}</div></div><div class="money">${cash(G.cash)}<small>${t('day')} ${num(G.day)}</small></div><button type="button" class="icon-button" data-action="go" data-page="settings" aria-label="${t('settings')}">${icon('settings')}</button></header>`;}
function nav(){const active=['plan','workshop','recipeReady'].includes(page)?'plan':['people','story','result','person'].includes(page)?'people':['legacy','memory','heirs','heir','ambitions','collection'].includes(page)?'legacy':'cafe';return `<nav class="navigation" aria-label="${t('brand')}">${[['cafe','cafe'],['plan','menu'],['people','people'],['legacy','book']].map(([id,ic])=>`<button type="button" data-action="go" data-page="${id}" ${active===id?'aria-current="page"':''}>${icon(ic)}<span>${t(id)}</span></button>`).join('')}</nav>`;}
function continuation(){return button('continue',t(G.phase==='planning'?'openDay':G.phase==='open'?'finishDay':'nextDay'));}
function footer(content){return `<footer class="footer">${content||continuation()}</footer>`;}
function render(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.title=t('brand');document.body.dataset.theme=G?.settings.theme||'light';document.body.dataset.text=G?.settings.textSize||'normal';document.documentElement.dataset.text=document.body.dataset.text;document.body.dataset.motion=G?.settings.reducedMotion?'reduce':'normal';send({type:'language',language:lang});const dark=G?.settings.theme==='dark'||G?.settings.theme==='auto'&&matchMedia('(prefers-color-scheme: dark)').matches;send({type:'appearance',theme:dark?'dark':'light'});document.querySelector('meta[name=theme-color]')?.setAttribute('content',dark?'#18251f':'#f8f3e9');if(!G){intro();return;}A?.configure(G.settings);let content='',foot='';switch(page){case'cafe':content=home();break;case'plan':content=planning();break;case'people':content=people();break;case'person':content=personPage();break;case'story':content=storyPage();foot=button('defer',t('keepForLater'),'outline');break;case'result':content=resultPage();foot=go('cafe',t('backCafe'),'primary');break;case'workshop':content=workshop();foot=button('create-recipe',t('addRecipe'));break;case'recipeReady':content=recipeReady();foot=button('put-recipe',t('putOnBoard'));break;case'legacy':content=legacy();break;case'memory':content=memoryPage();break;case'heirs':content=heirs();break;case'heir':content=heirPage();foot=button('inherit',t('beginChapter',{name:L(find('heirs',selectedHeir)?.name)}));break;case'ambitions':content=ambitions();break;case'settings':content=settings();break;case'export':content=exportPage();foot=button('copy',t('copy'));break;case'import':content=importPage();foot=button('import',t('restore'));break;case'legacyImport':content=legacyImport();foot=button('legacy-import',t('legacyRestore'));break;case'briefs':content=dailyBriefs();break;case'collection':content=collection();break;case'library':content=library();break;case'snapshot':content=snapshotPage();foot=button('open-snapshot',t('openSavedCafe'));break;case'removeSnapshot':content=removeSnapshotPage();foot=button('remove-snapshot',t('removeSavedCafe'),'outline');break;case'newCafe':content=newCafePage();foot=button('new-cafe-confirm',t('keepAndStart'));break;case'accounts':content=accounts();break;case'jump':content=jump();break;default:page='cafe';content=home();}
 const extra=foot&&page!=='heir'?`<button type="button" class="text-button wide" data-action="continue">${t('continue')}${icon('arrow')}</button>`:'';
 app.innerHTML=header()+(saveError?`<div class="save-warning">${t('saveFailed')}${go('export',t('export'),'text-button','', 'save')}</div>`:'')+`<main class="screen" id="screen" tabindex="-1">${content}</main>`+(notice?`<div class="notice" role="status">${icon('check')}<span>${esc(notice)}</span><button type="button" data-action="dismiss" aria-label="${t('dismissNotice')}">${icon('close')}</button></div>`:'')+footer((foot||continuation())+extra)+nav();send({type:'ready'});}
function intro(){app.innerHTML=`<main class="intro"><div class="lang-switch" aria-label="${t('language')}"><button type="button" data-action="intro-lang" data-value="en" lang="en" aria-pressed="${lang==='en'}">English</button><button type="button" data-action="intro-lang" data-value="ar" lang="ar" aria-pressed="${lang==='ar'}">العربية</button></div><img src="${brand('logo')}" class="brand-logo" alt=""><h1 class="title">${t('brand')}</h1><p class="description">${t('tagline')}</p><img class="intro-room" src="${art('room_1990s')}" alt=""><p class="description">${t('intro')}</p><label class="field"><span>${t('cafeName')}</span><input id="start-name" maxlength="40" value="${esc(draft.name??t('defaultCafe'))}" dir="auto"></label><label class="field"><span>${t('ownerName')}</span><input id="start-owner" maxlength="40" value="${esc(draft.owner??t('defaultOwner'))}" dir="auto"></label><label class="field"><span>${t('origin')}</span><select id="start-origin">${['family','independent','partner'].map(x=>`<option value="${x}" ${draft.origin===x?'selected':''}>${t(x)}</option>`).join('')}</select></label>${button('start',t('start'))}<p class="small">${t('offline')}</p>${get(OLD)?`<div class="card gap-top"><h3>${t('legacyFound')}</h3><p>${t('legacyDesc')}</p>${button('legacy-from-intro',t('legacyRestore'),'text-button','', 'archive')}</div>`:''}</main>`;send({type:'ready'});}
function scene(){const live=G.phase==='open'?G.service:G,venue=find('venues',live.venue||G.venue),layout=find('layouts',live.layout||G.layout);const roomArt=(live.venue||G.venue)!=='home'?venue?.art:layout?.art;const ps=C.characters.filter(p=>E.personStatus(G,p.id)?.active).slice(0,2);const installed=[...new Map(G.upgrades.map(id=>find('upgrades',id)).filter(Boolean).map(u=>[u.art,u])).values()];return `<section class="hero" aria-label="${esc(G.cafeName)}">${img(roomArt||'room_day','','')}<div class="installed-props" aria-hidden="true">${installed.map(u=>img(u.art,'prop prop-'+u.art)).join('')}</div><div class="scene-top"><span class="scene-chip">${esc(date(G.date,true))} · ${t(E.seasonFor(G.date))}</span><button type="button" class="scene-action" data-action="panel" data-panel="room" aria-label="${t('arrange')}">${icon('room')}</button></div><button type="button" class="room-hotspot" data-action="panel" data-panel="menu" aria-label="${t('menu')}">${icon('menu')}</button><div class="scene-people">${ps.map(p=>`<button type="button" class="visitor" data-action="person" data-id="${p.id}">${img(p.art)}<span>${esc(L(p.name))}</span></button>`).join('')}${!ps.length?`<span class="scene-chip">${t('familyVisitor')}</span>`:''}</div></section>`;}
function nextStoryDays(){if(stories().length)return 0;const days=[...new Set(C.stories.concat(C.events).map(s=>s.minDay||1).filter(day=>day>G.day))].sort((a,b)=>a-b);for(const day of days){const delta=day-G.day;if(E.availableStories({...G,day,date:E.advanceDate(G.date,delta)}).length)return delta;}return null;}
function opportunityLink(){return nextStoryDays()===null?`<p class="small">${t('chapterComplete')}</p>${go('workshop',t('createRecipe'),'text-button start','', 'spark')}${go('heirs',t('nextGeneration'),'text-button start','', 'people')}`:go('jump',t('nextOpportunity'),'text-button start','', 'clock');}
function recipeFacts(r){return `<span class="recipe-facts">${t('price')}: ${cash(r.price)} · ${t('cost')}: ${cash(r.cost)}<br>${(r.tags||[]).map(tag=>esc(t(`tag_${tag}`))).join(' · ')}</span>`;}
function planningBrief(){const next={...G,phase:'planning',date:G.phase==='planning'?G.date:E.advanceDate(G.date,1)},f=E.forecast(next);return `<div class="planning-forecast"><span class="section-label">${t(G.phase==='planning'?'planForecast':'tomorrowForecast')}</span><div class="brief"><div><strong>${num(f.customers)}</strong><span>${t('expectedGuests')}</span></div><div><strong>${cash(f.profit)}</strong><span>${t('expectedTakeHome')}</span></div><div><strong>${num(Math.round(f.fit*100))}%</strong><span>${t('guestFit')}</span></div></div><p class="small">${t('forecastHint')}</p></div>`;}
function home(){if(G.phase==='closed')return closeSummary();const f=E.forecast(G),available=stories(),featured=available.find(x=>x.id===G.pendingStory)||available[0];let out=`<div class="morning-title"><div class="eyebrow">${t(G.phase==='planning'?'planning':'today')}</div><h1 class="title">${G.phase==='planning'?t('morning',{name:esc(G.owner)}):t('open')}</h1></div>${scene()}`;
 if(G.phase==='open'){const guest=E.currentGuest(G),p=guest&&person(guest.characterId);out+=`<section class="service-card">${guest?`<div class="guest-head">${img(p?.art||'p4','avatar')}<div class="grow"><div class="eyebrow">${t('guest')} ${num(G.service.index+1)} / ${num(G.service.guests.length)}</div><h2 class="subtitle">${esc(L(guest.name||p?.name))}</h2><p class="small gap-top">${t('serviceHint')}</p></div></div><div class="service-options">${G.service.menu.map(id=>{const r=recipe(id);return `<button type="button" class="serve-button ${guest.recommended===id?'recommended':''}" data-action="serve" data-id="${id}">${img(r.art)}<strong>${esc(L(r.name))}</strong><small>${guest.usual===id?t('yourUsual'):guest.recommended===id?t('goodMatch'):'&nbsp;'}</small></button>`;}).join('')}</div>`:`<div class="stat-stamp">${icon('check')}</div><h2 class="subtitle">${t('serviceComplete')}</h2><p class="description">${t('serviceCompleteDesc')}</p>`}<div class="day-progress" aria-label="${num(G.service.index)} / ${num(G.service.guests.length)}">${G.service.guests.map((_,i)=>`<span class="${i<G.service.index?'done':''}"></span>`).join('')}</div><p class="small gap-top">${t('noTimers')}</p></section>`;return out;}
 out+=`<div class="brief"><div><strong>${num(f.customers)}</strong><span>${t('expectedGuests')}</span></div><div><strong>${cash(f.profit)}</strong><span>${t('expectedTakeHome')}</span></div><div><strong>${num(G.seats)}</strong><span>${t('seats')}</span></div></div><div class="mini-board">${G.menu.slice(0,4).map(id=>img(recipe(id)?.art)).join('')}${button('panel',t('plan'),'text-button','data-panel="menu"','arrow')}</div>`;
 out+=dailyBriefCard();
 if(featured){const p=person(featured.character||featured.characterId);out+=`<div class="story-teaser">${img(p?.art||'p11','avatar')}<div class="teaser-body"><div class="eyebrow">${t('someoneToSee')}</div><h2 class="subtitle">${esc(L(featured.title))}</h2>${button('story',t('hearStory'),'text-button start',`data-id="${featured.id}"`)}</div></div>`;}else out+=`<div class="padded"><p class="small">${t('keepCreating')}</p>${opportunityLink()}</div>`;return out;}
function closeSummary(){const f=G.lastDay||E.forecast(G);return `<section class="padded"><div class="stat-stamp">${icon('sun')}</div><div class="eyebrow">${date(G.date)}</div><h1 class="title">${t('closed')}</h1><p class="description">${t('resultDesc')}</p><div class="brief" style="margin-inline:0"><div><strong>${num(f.customers)}</strong><span>${t('guests')}</span></div><div><strong>${cash(f.profit)}</strong><span>${t('takeHome')}</span></div></div>${ledger(f)}${briefOutcome()}${f.coveredShortfall?`<p class="small gap-top">${t('safeMonth')}</p>`:''}${go('accounts',t('accounts'),'text-button start','', 'book')}<div class="card gap-top"><div class="row">${icon('heart')}<h3>${t('newPage')}</h3></div><p>${t('ledgerNote')}</p></div></section>`;}
function ledger(f){const b=f.breakdown||{};return `<div class="ledger">${[['sales',f.sales],['ingredients',b.ingredients],['rent',b.rent],['wages',b.wages],['supplier',b.supplier],['operating',b.operating]].map(([k,v])=>`<div class="ledger-row"><span>${t(k)}</span><span>${k==='sales'?'':'− '}${cash(v)}</span></div>`).join('')}<div class="ledger-row total"><span>${t('takeHome')}</span><span>${cash(f.profit)}</span></div></div>`;}
function planning(){let out=`<div class="padded"><div class="eyebrow">${date(G.date,true)}</div><h1 class="title">${t('planTitle')}</h1></div><div class="plan-tabs" aria-label="${t('plan')}">${['menu','room','team','suppliers','shop','venues'].map(id=>`<button type="button" data-action="panel" data-panel="${id}" aria-pressed="${panel===id}">${t(id)}</button>`).join('')}</div><section class="padded" style="padding-top:0">${G.phase==='open'?`<p class="note">${icon('clock')}${t('futureMenu')}</p>`:''}${planningBrief()}`;if(panel==='menu')out+=menu();else if(panel==='room')out+=room();else if(panel==='team')out+=team();else if(panel==='suppliers')out+=suppliers();else if(panel==='shop')out+=shop();else if(panel==='venues')out+=venues();return out+'</section>';}
function menu(){return `<div class="menu-board"><div class="spread"><h2 class="subtitle">${t('onBoard')}</h2><span class="small">${num(G.menu.length)} / ${num(G.boardSlots)}</span></div><div class="board-slots">${G.menu.map(id=>{const r=recipe(id);return `<button type="button" class="board-slot ${selectedRecipe?'swappable':''}" data-action="menu-slot" data-id="${id}" aria-label="${esc(L(r.name))}">${img(r.art)}<strong>${esc(L(r.name))}</strong><small>${cash(r.price)}</small></button>`;}).join('')}${G.menu.length<G.boardSlots?`<button type="button" class="board-slot" data-action="empty-slot" aria-label="${t('add')}">${icon('plus')}<strong>${t('add')}</strong></button>`:''}</div></div><p class="note">${icon(selectedRecipe?'arrow':'heart')}${t(selectedRecipe?'swapHint':'foreverRecipes')}</p><div class="spread"><span class="section-label">${t('recipeBook')}</span><span class="small">${num(allRecipes().length)}</span></div>${allRecipes().map(r=>`<button type="button" class="recipe-row" data-action="menu-recipe" data-id="${r.id}">${img(r.art)}<span class="list-copy"><h3>${esc(L(r.name))}</h3><p>${esc(L(r.description))}</p>${recipeFacts(r)}</span><span class="list-end">${icon(G.menu.includes(r.id)?'check':'plus')}<small>${t(G.menu.includes(r.id)?'onMenu':'add')}</small></span></button>`).join('')}<div class="gap-top">${go('workshop',t('createRecipe'),'secondary','', 'spark')}</div>`;}
function room(){return `<h2 class="subtitle">${t('arrange')}</h2><img class="layout-preview" src="${art(find('layouts',G.layout)?.art||'room_day')}" alt=""><div class="stack">${C.layouts.map(x=>`<button type="button" class="card choice ${G.layout===x.id?'selected':''}" data-action="layout" data-id="${x.id}" aria-pressed="${G.layout===x.id}">${img(x.art||'f_table_lg')}<span class="list-copy"><h3>${esc(L(x.name))}</h3><p>${esc(L(x.description))}</p><span class="tag">${icon(G.layout===x.id?'check':'plus')}${t(G.layout===x.id?'inUse':'placeNow')}</span></span></button>`).join('')}</div>`;}
function team(){return `<p class="description">${t('staffIntro')}</p><div class="stack gap-top">${Object.entries(E.STAFF).map(([id,d])=>`<div class="card"><h3>${t(id)}</h3><p>${t(id+'Desc')}</p><p>${t('wage')}: ${cash(d.wage)}</p><div class="gap-top">${G.staff.includes(id)?`<span class="pill">${icon('check')}${t('hired')}</span>`:button('hire',t('hire')+' · '+cash(d.cost),'secondary',`data-id="${id}"`)}</div></div>`).join('')}</div>`;}
function suppliers(){return `<p class="description">${t('supplierIntro')}</p><div class="stack gap-top">${C.suppliers.map(x=>`<button type="button" class="card ${G.supplier===x.id?'selected':''}" data-action="supplier" data-id="${x.id}" aria-pressed="${G.supplier===x.id}"><h3>${esc(L(x.name))}</h3><p>${esc(L(x.description))}</p><span class="tag">${icon(G.supplier===x.id?'check':'leaf')}${t('dailyFee')}: ${cash(x.fee)}</span></button>`).join('')}</div>`;}
function shop(){return `<p class="description">${t('improvementsIntro')}</p><div class="stack gap-top">${C.upgrades.map(x=>`<div class="card"><div class="row">${img(x.art||'f_menuboard','upgrade-art')}<div class="list-copy"><h3>${esc(L(x.name))}</h3><p>${esc(L(x.description))}</p></div></div><div class="gap-top">${G.upgrades.includes(x.id)?`<span class="pill">${icon('check')}${t('owned')}</span>`:button('buy',t('buyFor',{cash:cash(x.cost)}),'secondary',`data-id="${x.id}"`)}</div></div>`).join('')}</div>`;}
function venues(){return `<h2 class="subtitle">${t('newSpace')}</h2><div class="stack gap-top">${C.venues.map(x=>`<div class="card">${img(x.art||'room_1990s','layout-preview')}<h3>${esc(L(x.name))}</h3><p>${esc(L(x.description))}</p><div class="gap-top">${G.venues.includes(x.id)?(G.venue===x.id?`<span class="pill">${icon('check')}${t('activeVenue')}</span>`:button('visit',t('visit'),'secondary',`data-id="${x.id}"`)):button('buy-venue',t('buyFor',{cash:cash(x.cost)}),'secondary',`data-id="${x.id}"`)}</div></div>`).join('')}</div>`;}
function people(){return `<section class="padded"><div class="eyebrow">${t('neighbourhood')}</div><h1 class="title">${t('peopleTitle')}</h1>${C.characters.map(p=>{const status=E.personStatus(G,p.id),available=stories().find(s=>(s.character||s.characterId)===p.id);return `<button type="button" class="list-row" data-action="person" data-id="${p.id}">${img(p.art,'avatar')}<span class="list-copy"><h3>${esc(L(status.active?p.name:status.descendant.name))}</h3><p>${esc(available?L(available.title):status.active?L(p.role):t('familyVisitor'))}</p></span>${icon(available?'arrow':'heart')}</button>`;}).join('')}<div class="section-label gap-top">${t('opportunities')}</div><div class="stack gap-top">${stories().filter(s=>!s.character&&!s.characterId).slice(0,4).map(s=>button('story',esc(L(s.title)),'outline',`data-id="${s.id}"`)).join('')||`<p class="small">${t('allCaughtUp')}</p>`}</div>${opportunityLink()}</section>`;}
let personId='mariam';
function personPage(){const p=person(personId)||C.characters[0],status=E.personStatus(G,p.id),available=stories().filter(s=>(s.character||s.characterId)===p.id);return `<section class="padded">${back('people')}<div class="eyebrow">${t('neighbourhood')}</div><div class="person-feature">${img(p.art,'avatar')}<div><h1 class="subtitle">${esc(L(status.active?p.name:status.descendant.name))}</h1><p class="description">${esc(status.active?L(p.role):t('familyVisitor'))}</p></div></div><div class="stack gap-top">${available.map(s=>button('story',esc(L(s.title)),'outline',`data-id="${s.id}"`)).join('')||`<p class="description">${t('allCaughtUp')}</p><p class="small">${t('keepCreating')}</p>`}</div><div class="section-label gap-top">${t('memories')}</div>${G.memories.filter(m=>m.storyId&&m.storyId.startsWith(p.id+'-')).map(memoryRow).join('')||`<p class="small gap-top">${t('noMemories')}</p>`}</section>`;}
function storyPage(){const s=stories().find(x=>x.id===storyId);if(!s){page='people';return people();}const p=person(s.character||s.characterId);return `<section class="padded">${back('people')}<div class="eyebrow">${esc(p?L(p.name):t('opportunities'))}</div><h1 class="title">${esc(L(s.title))}</h1><div class="dialogue">${img(p?.art||'p11','avatar')}<p class="quote">${esc(L(s.body))}</p></div><div class="stack">${s.choices.map(ch=>`<button type="button" class="card choice" data-action="choose" data-id="${ch.id}"><span class="list-copy"><h3>${esc(L(ch.label))}</h3><p>${esc(L(ch.description))}</p><span class="tag">${icon(ch.kind==='recipe'?'menu':ch.kind==='street'?'leaf':'people')}${t(ch.kind==='recipe'?'recipes':ch.kind==='street'?'opportunities':'people')}</span></span>${icon('arrow')}</button>`).join('')}</div><p class="small gap-top">${t('chooseApproach')}</p></section>`;}
function photo(text,when){return `<div class="polaroid"><div class="polaroid-picture">${img('room_1990s')}<div class="polaroid-people">${['p4','p2','p3','p5'].map(x=>img(x)).join('')}</div></div><h3>${esc(L(text))}</h3><p class="small">${esc(date(when||G.date,true))} · <bdi>${esc(G.cafeName)}</bdi></p></div>`;}
function resultPage(){if(!result)return legacy();return `<section class="padded"><div class="eyebrow">${t('storyResult')}</div><h1 class="title">${esc(L(result.story.title))}</h1><p class="description">${esc(L(result.choice.result))}</p>${result.choice.rewardCash?`<p class="note">${icon('coin')}${t('storyReward',{cash:cash(result.choice.rewardCash)})}</p>`:''}${photo(result.choice.memory||result.story.title,result.date)}<div class="result-line">${icon('book')}<div>${t('memorySaved')}<small>${result.choice.recipe?t('newRecipe'):t('newPage')}</small></div></div>${go('legacy',t('familyBook'),'text-button start','', 'book')}</section>`;}
function segments(key,label,values){return `<fieldset><legend>${t(label)}</legend><div class="segments">${values.map(v=>`<button type="button" data-action="ingredient" data-key="${key}" data-value="${v}" aria-pressed="${form[key]===v}">${t(v)}</button>`).join('')}</div></fieldset>`;}
function workshop(){const preview=E.dispatch(G,{type:'CREATE_RECIPE',name:form.name||t('houseName'),...form}),r=preview.error?G.customRecipes.find(x=>x.combination===[form.base,form.flavour,form.temperature].join(':')):preview.state.customRecipes.at(-1);const picture=form.base==='coffee'?'espresso':form.base==='fruit'?'roselem':form.flavour==='saffron'?'saffron':'karak';return `<section class="padded">${back('plan')}<div class="eyebrow">${t('workshop')}</div><h1 class="title">${t('workshopTitle')}</h1><div class="workshop-preview">${img(picture)}<div><div class="eyebrow">${t('houseCreation')}</div><h2 class="subtitle" id="recipe-preview-name" dir="auto">${esc(form.name||t('houseName'))}</h2><p>${t(form.base)} · ${t(form.flavour)} · ${t(form.temperature)}</p></div></div>${r?recipeFacts(r):''}${segments('base','startWith',['tea','coffee','milk','fruit'])}${segments('flavour','flavour',['cardamom','rose','date','saffron','mint','chocolate'])}${segments('temperature','temperature',['hot','cold'])}<label class="field"><span>${t('recipeName')}</span><input id="recipe-name" maxlength="48" value="${esc(form.name)}" placeholder="${t('houseName')}" dir="auto"></label><p class="small gap-top">${t('instantRecipe')}</p></section>`;}
function recipeReady(){const r=recipe(lastRecipe);if(!r)return workshop();return `<section class="padded"><div class="stat-stamp">${icon('check')}</div><div class="eyebrow">${t('houseCreation')}</div><h1 class="title">${t('recipeReady')}</h1><div class="workshop-preview">${img(r.art)}<div><h2 class="subtitle" dir="auto">${esc(L(r.name))}</h2><p>${esc(L(r.description))}</p></div></div><div class="result-line">${icon('book')}<div>${t('memorySaved')}<small>${t('foreverRecipes')}</small></div></div>${go('workshop',t('tryAnother'),'text-button wide','', 'spark')}</section>`;}
function memoryRow(m){const r=m.recipeId?recipe(m.recipeId):null;return `<button type="button" class="list-row" data-action="memory" data-id="${esc(m.id)}">${img(r?.art||'room_1990s','memory-thumb')}<span class="list-copy"><h3 dir="auto">${esc(L(m.text))}</h3><p>${esc(date(m.date,true))}</p></span>${icon('arrow')}</button>`;}
function legacy(){return `<section class="padded"><div class="eyebrow">${t('familyBook')} · ${t('generation')} ${num(G.generation)}</div><h1 class="title">${t('legacyTitle')}</h1><div class="person-feature">${img('p_keys','upgrade-art')}<div><h2 class="subtitle" dir="auto">${t('yourChapter',{name:esc(G.owner)})}</h2><p class="description">${t('legacyIntro')}</p></div></div><div class="brief" style="margin-inline:0"><div><strong>${num(G.daysRun)}</strong><span>${t('finishedDays')}</span></div><div><strong>${num(G.memories.length)}</strong><span>${t('memories')}</span></div><div><strong>${num(allRecipes().length)}</strong><span>${t('recipes')}</span></div></div>${go('collection',t('collectionTitle'),'secondary gap-top','', 'flag')}${go('heirs',t('nextGeneration'),'secondary gap-top','', 'people')}${go('ambitions',t('ambitions'),'text-button start','', 'flag')}<div class="section-label gap-top">${t('memories')}</div>${G.memories.slice().reverse().map(memoryRow).join('')||`<p class="description empty">${t('noMemories')}</p>`}${G.legacy?`<div class="card gap-top"><h3>${t('familyArchive')}</h3><p>${t('legacyDesc')}</p>${button('original-export',t('legacyExport'),'text-button wide','', 'archive')}</div>`:''}</section>`;}
function memoryPage(){const m=G.memories.find(x=>x.id===memoryId);return `<section class="padded">${back('legacy')}<div class="eyebrow">${t('remembered')}</div>${m?photo(m.text,m.date):`<p>${t('noMemories')}</p>`}<p class="small center">${t('legacyIntro')}</p></section>`;}
function heirs(){return `<section class="padded">${back('legacy')}<div class="eyebrow">${t('nextGeneration')}</div><h1 class="title">${t('successionTitle')}</h1><p class="description">${t('successionNote')}</p><div class="stack gap-top">${C.heirs.map(h=>`<button type="button" class="card choice" data-action="heir" data-id="${h.id}">${img(h.art||'p5','avatar')}<span class="list-copy"><h3>${esc(L(h.name))}</h3><p>${esc(L(h.description))}</p></span>${icon('arrow')}</button>`).join('')}</div></section>`;}
function heirPage(){const h=find('heirs',selectedHeir)||C.heirs[0];return `<section class="padded">${back('heirs')}<div class="eyebrow">${t('nextGeneration')}</div><h1 class="title">${t('successionTitle')}</h1><div class="person-feature">${img(h.art||'p5','avatar')}<div><h2 class="subtitle">${esc(L(h.name))}</h2><p class="description">${esc(L(h.description))}</p></div></div><div class="section-label gap-top">${t('inheritAll')}</div><div class="inherit-list">${['allCash','allRecipes','allTools','allSpaces','allKnowledge','allMemories'].map(k=>`<span>${icon('check')}${t(k)}</span>`).join('')}</div><p class="description">${t('successionNote')}</p></section>`;}
function ambitions(){const counts={days:G.daysRun,stories:G.storiesDone.length,customRecipes:G.customRecipes.length,recipes:allRecipes().length,upgrades:G.upgrades.length,venues:G.venues.length,generation:G.generation,served:G.totalServed};return `<section class="padded">${back('legacy')}<div class="eyebrow">${t('progress')}</div><h1 class="title">${t('ambitions')}</h1><div class="stack gap-top">${C.ambitions.map(a=>`<div class="card ${G.ambitionsDone.includes(a.id)?'selected':''}"><div class="row">${icon(G.ambitionsDone.includes(a.id)?'check':'flag')}<h3>${esc(L(a.name))}</h3></div><p>${esc(L(a.description))}</p><div class="tag">${G.ambitionsDone.includes(a.id)?t('achieved'):num(Math.min(counts[a.kind]||0,a.target))+' / '+num(a.target)}</div></div>`).join('')}</div></section>`;}
function accounts(){return `<section class="padded">${back()}<div class="eyebrow">${t('accounts')}</div><h1 class="title">${t('monthSoFar')}</h1><div class="ledger">${[['finishedDays',G.monthly.days],['sales',G.monthly.sales],['costs',G.monthly.costs],['takeHome',G.monthly.profit]].map(([k,v])=>`<div class="ledger-row"><span>${t(k)}</span><span>${k==='finishedDays'?num(v):cash(v)}</span></div>`).join('')}</div><p class="small gap-top">${t('ledgerNote')}</p>${G.accounts.slice().reverse().map(a=>`<div class="card gap-top"><h3>${esc(a.month)}</h3><p>${t('takeHome')}: ${cash(a.profit)} · ${num(a.days)} ${t('finishedDays')}</p></div>`).join('')}</section>`;}
function jump(){return `<section class="padded">${back()}<div class="eyebrow">${t('team')}</div><h1 class="title">${t('jumpTitle')}</h1><p class="description">${t('jumpDesc')}</p><div class="stack gap-top">${nextStoryDays()===null?opportunityLink():button('next-story',t('nextOpportunity'),'secondary','', 'people')}${button('jump',t('oneWeek'),'outline','data-days="7"','clock')}${button('jump',t('oneMonth'),'outline','data-days="30"','clock')}</div></section>`;}
function settings(){return `<section class="padded">${back()}<div class="eyebrow">${t('brand')}</div><h1 class="title">${t('settings')}</h1><div class="settings-row"><label for="setting-lang">${t('language')}</label><select id="setting-lang" data-pref="lang"><option value="en" ${lang==='en'?'selected':''}>English</option><option value="ar" ${lang==='ar'?'selected':''}>العربية</option></select></div>${['music','sfx','haptics','reducedMotion'].map(k=>`<div class="settings-row"><label for="setting-${k}">${t(k)}${S[k+'Desc']?`<small>${t(k+'Desc')}</small>`:''}</label><input type="checkbox" id="setting-${k}" data-pref="${k}" ${G.settings[k]?'checked':''}></div>`).join('')}<div class="settings-row"><label for="setting-size">${t('textSize')}</label><select id="setting-size" data-pref="textSize">${['normal','large','larger'].map(x=>`<option value="${x}" ${G.settings.textSize===x?'selected':''}>${t(x)}</option>`).join('')}</select></div><div class="settings-row"><label for="setting-theme">${t('theme')}</label><select id="setting-theme" data-pref="theme">${['light','dark','auto'].map(x=>`<option value="${x}" ${G.settings.theme===x?'selected':''}>${t(x)}</option>`).join('')}</select></div>${button('test-sound',t('playAudio'),'text-button start','', 'volume')}<label class="field"><span>${t('cafeName')}</span><input id="rename-cafe" maxlength="40" value="${esc(G.cafeName)}" dir="auto"></label><label class="field"><span>${t('ownerName')}</span><input id="rename-owner" maxlength="40" value="${esc(G.owner)}" dir="auto"></label>${button('rename',t('save'),'secondary gap-top','', 'check')}<div class="section-label gap-top">${t('backup')}</div>${go('library',t('savedCafes'),'text-button start','', 'book')}${go('newCafe',t('startAnotherCafe'),'text-button start','', 'plus')}${go('export',t('export'),'text-button start','', 'save')}${go('import',t('import'),'text-button start','', 'archive')}${get(ARCHIVE)?button('backup-export',t('previousCafe'),'text-button start','', 'archive'):''}${get(OLD)?go('legacyImport',t('legacyRestore'),'text-button start','', 'book'):''}${go('jump',t('jumpTitle'),'text-button start','', 'clock')}<p class="small gap-top">${t('privacy')}</p></section>`;}
function exportPage(){let raw=exportSnapshot|| (exportBackup?get(ARCHIVE):exportOriginal?(G.legacy?JSON.stringify(G.legacy.original):get(OLD)||''):E.exportSave(G));return `<section class="padded">${back('settings')}<div class="eyebrow">${t('backup')}</div><h1 class="title">${t(exportBackup?'previousCafe':exportOriginal?'legacyExport':'export')}</h1><p class="description">${t('exportDesc')}</p>${!exportOriginal?button('share-save',t(window.CAFE_NATIVE_CAPABILITIES?.saveFiles?'saveFile':'downloadFile'),'secondary gap-top','', 'save'):''}<label class="field"><span>${t('copyManual')}</span><textarea id="save-text" readonly spellcheck="false">${esc(raw)}</textarea></label></section>`;}
function importPage(){return `<section class="padded">${back('settings')}<h1 class="title">${t('import')}</h1><p class="description">${t('importDesc')}</p>${button('pick-save',t('openFile'),'secondary gap-top','', 'archive')}<input id="save-file" type="file" accept=".json,.cafelife,application/json,text/plain" hidden><label class="field"><span>${t('backup')}</span><textarea id="import-text" spellcheck="false">${esc(importDraft)}</textarea></label></section>`;}
function legacyImport(){return `<section class="padded">${back('settings')}<h1 class="title">${t('legacyFound')}</h1><p class="description">${t('legacyDesc')}</p>${button('original-export',t('legacyExport'),'secondary gap-top','', 'archive')}</section>`;}
function navigate(target){page=target;if(target==='export'){exportOriginal=false;exportBackup=false;exportSnapshot=null;}notice='';render();document.getElementById('screen')?.focus({preventScroll:true});}
function soundGesture(){try{A?.unlock();}catch(_){}}
app.addEventListener('input',event=>{if(event.target.id==='import-text')importDraft=event.target.value;if(event.target.id==='recipe-name'){form.name=event.target.value;const el=document.getElementById('recipe-preview-name');if(el)el.textContent=form.name||t('houseName');}});
app.addEventListener('change',async event=>{if(event.target.id==='save-file'){const file=event.target.files?.[0];if(file){if(file.size>25000000){notice=t('fileTooLarge');render();return;}try{receiveImport(await file.text());}catch(_){notice=t('fileError');render();}}return;}const key=event.target.dataset.pref;if(!key)return;soundGesture();dispatch({type:'SET_PREF',key,value:event.target.type==='checkbox'?event.target.checked:event.target.value});});
app.addEventListener('click',async event=>{const b=event.target.closest('button[data-action]');if(!b)return;soundGesture();const a=b.dataset.action;notice='';
 if(a==='intro-lang'){const name=document.getElementById('start-name').value,owner=document.getElementById('start-owner').value;draft={name:name===t('defaultCafe')?undefined:name,owner:owner===t('defaultOwner')?undefined:owner,origin:document.getElementById('start-origin').value};lang=b.dataset.value;render();return;}
 if(a==='start'){start({name:document.getElementById('start-name').value,owner:document.getElementById('start-owner').value,origin:document.getElementById('start-origin').value,lang});return;}
 if(a==='legacy-from-intro'){try{G=E.migrateLegacy(JSON.parse(get(OLD)),{lang});page='cafe';notice=t('legacyImported');persist();render();}catch(_){notice=t('unsupportedLegacy');intro();const p=document.createElement('p');p.className='description';p.textContent=notice;app.querySelector('.intro').appendChild(p);const label=document.createElement('label');label.className='field';label.textContent=t('legacyExport');const area=document.createElement('textarea');area.readOnly=true;area.value=get(OLD)||'';label.appendChild(area);app.querySelector('.intro').appendChild(label);}return;}
 if(!G)return;
 if(a==='go'){navigate(b.dataset.page);A?.play('tap');return;}
 if(a==='dismiss'){render();return;}
 if(a==='continue'){page='cafe';dispatch({type:'CONTINUE'});return;}
 if(a==='panel'){panel=b.dataset.panel;page='plan';render();return;}
 if(a==='menu-recipe'){const id=b.dataset.id;if(G.menu.includes(id)){notice=L(recipe(id).description);}else if(G.menu.length<G.boardSlots){notice=t('boardUpdated');dispatch({type:'SET_MENU',ids:G.menu.concat(id)});return;}else selectedRecipe=id;render();return;}
 if(a==='menu-slot'){if(selectedRecipe){const ids=G.menu.map(id=>id===b.dataset.id?selectedRecipe:id);selectedRecipe=null;notice=t('boardUpdated');dispatch({type:'SET_MENU',ids});}else{notice=L(recipe(b.dataset.id).description);render();}return;}
 if(a==='empty-slot'){notice=t('recipeBook');render();return;}
 if(a==='layout'){notice=t('roomUpdated');dispatch({type:'SET_LAYOUT',id:b.dataset.id});return;}
 if(a==='supplier'){notice=t('supplierUpdated');dispatch({type:'SET_SUPPLIER',id:b.dataset.id});return;}
 if(a==='buy'||a==='buy-venue'){notice=t('purchased');dispatch({type:a==='buy'?'BUY_UPGRADE':'BUY_VENUE',id:b.dataset.id});return;}
 if(a==='visit'){notice=t('venueChanged');dispatch({type:'SWITCH_VENUE',id:b.dataset.id});return;}
 if(a==='hire'){notice=t('hiredNotice');dispatch({type:'HIRE',id:b.dataset.id});return;}
 if(a==='serve'){const guest=E.currentGuest(G);notice=t(guest?.usual===b.dataset.id?'usualNotice':'servedNotice');dispatch({type:'SERVE',recipeId:b.dataset.id});return;}
 if(a==='person'){personId=b.dataset.id;page='person';render();return;}
 if(a==='story'){storyId=b.dataset.id;page='story';dispatch({type:'TALK',id:storyId});return;}
 if(a==='choose'){const story=stories().find(s=>s.id===storyId),choice=story?.choices.find(ch=>ch.id===b.dataset.id);if(!choice)return;result={story,choice,date:G.date};page='result';dispatch({type:'CHOOSE',storyId,choiceId:choice.id});return;}
 if(a==='defer'){page='cafe';notice=t('storySaved');render();return;}
 if(a==='ingredient'){form[b.dataset.key]=b.dataset.value;render();return;}
 if(a==='create-recipe'){const r=dispatch({type:'CREATE_RECIPE',name:form.name||t('houseName'),base:form.base,flavour:form.flavour,temperature:form.temperature});if(!r.error){lastRecipe=r.effects.find(x=>x.type==='recipe')?.id;page='recipeReady';render();}return;}
 if(a==='put-recipe'){panel='menu';page='plan';if(G.menu.length<G.boardSlots){dispatch({type:'SET_MENU',ids:G.menu.concat(lastRecipe)});}else{selectedRecipe=lastRecipe;render();}return;}
 if(a==='memory'){memoryId=b.dataset.id;page='memory';render();return;}
 if(a==='heir'){selectedHeir=b.dataset.id;page='heir';render();return;}
 if(a==='inherit'){page='cafe';notice=t('generationStarted');dispatch({type:'SUCCESSION',id:selectedHeir});return;}
 if(a==='rename'){notice=t('nameSaved');dispatch({type:'RENAME',name:document.getElementById('rename-cafe').value,owner:document.getElementById('rename-owner').value});return;}
 if(a==='jump'){page='cafe';notice=t('jumpDone');dispatch({type:'JUMP',days:Number(b.dataset.days)});return;}
 if(a==='next-story'){const days=nextStoryDays();if(days===null){page='jump';render();return;}if(days>0){const r=dispatch({type:'JUMP',days});if(r.error)return;}if(stories().length){storyId=stories()[0].id;page='story';dispatch({type:'TALK',id:storyId});}return;}
 if(a==='copy'){const el=document.getElementById('save-text');try{await navigator.clipboard.writeText(el.value);notice=t('copied');render();}catch(_){el.focus();el.select();announce(t('copyManual'));}return;}
 if(a==='import'){const raw=document.getElementById('import-text').value;try{E.importSave(raw);}catch(_){notice=t('invalidSave');render();return;}try{G=P.replace(raw,G);lang=G.lang;saveError=false;importDraft='';page='cafe';notice=t('restored');render();}catch(_){notice=t('libraryFailed');render();}return;}
 if(a==='backup-export'){exportSnapshot=null;exportOriginal=false;exportBackup=true;page='export';render();return;}
 if(a==='original-export'){exportSnapshot=null;exportBackup=false;exportOriginal=true;page='export';render();return;}
 if(a==='legacy-import'){try{const candidate=E.migrateLegacy(JSON.parse(get(OLD)),{lang});G=P.replace(E.exportSave(candidate),G);page='cafe';notice=t('legacyImported');render();}catch(_){notice=t('unsupportedLegacy');render();}return;}
 if(a==='select-brief'){dispatch({type:'SELECT_BRIEF',id:b.dataset.id});return;}
 if(a==='clear-brief'){dispatch({type:'CLEAR_BRIEF'});return;}
 if(a==='keep-cafe'){try{P.keep(G);notice=t('cafeKept');}catch(_){notice=t('libraryFailed');}render();return;}
 if(a==='snapshot'){snapshotId=b.dataset.id;page='snapshot';render();return;}
 if(a==='snapshot-export'){try{exportSnapshot=P.snapshot(snapshotId);exportOriginal=false;exportBackup=false;page='export';render();}catch(_){notice=t('libraryFailed');render();}return;}
 if(a==='open-snapshot'){try{G=P.replace(P.snapshot(snapshotId),G);saveError=false;lang=G.lang;page='cafe';notice=t('restored');selectedRecipe=null;render();}catch(_){notice=t('libraryFailed');render();}return;}
 if(a==='remove-snapshot'){try{P.remove(snapshotId);page='library';notice=t('snapshotRemoved');render();}catch(_){notice=t('libraryFailed');render();}return;}
 if(a==='new-cafe-confirm'){try{const next=E.newGame({name:document.getElementById('new-name').value,owner:document.getElementById('new-owner').value,origin:document.getElementById('new-origin').value,lang});next.settings={...G.settings};G=P.replace(E.exportSave(next),G);saveError=false;page='cafe';selectedRecipe=null;notice=t('previousCafeKept');render();A?.play('open');}catch(_){notice=t('libraryFailed');render();}return;}
 if(a==='pick-save'){if(window.CAFE_NATIVE_CAPABILITIES?.saveFiles){nativeRequest('pickSave');}else document.getElementById('save-file').click();return;}
 if(a==='share-save'){try{const text=document.getElementById('save-text').value,name='Cafe-Life-'+E.importSave(text).date+'.cafelife.json';if(window.CAFE_NATIVE_CAPABILITIES?.saveFiles){nativeRequest('exportSave',{text,filename:name});return;}const file=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(file),link=document.createElement('a');link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);notice=t('exportOpened');render();}catch(_){notice=t('fileError');render();}return;}
 if(a==='test-sound'){A?.play('success');return;}
});

function dailyBriefCard(){const b=E.briefStatus?.(G);return `<div class="daily-card"><div class="row">${icon('flag')}<div class="grow"><div class="eyebrow">${t('todayBrief')}</div><h3>${b?esc(L(b.title)):t('makeTodaySpecial')}</h3><p class="small">${b?t(b.ready?'briefReady':'briefInProgress'):t('optionalBrief')}</p></div>${go('briefs',t(b?'viewBrief':'chooseBrief'),'text-button','', 'arrow')}</div></div>`;}
function dailyBriefs(){const selected=E.briefStatus(G);return `<section class="padded">${back()}<div class="eyebrow">${t('todayBrief')}</div><h1 class="title">${t('makeTodaySpecial')}</h1><p class="description">${t('optionalBrief')}</p><div class="stack gap-top">${E.dailyBriefs(G).map(b=>`<div class="card ${selected?.id===b.id?'selected':''}"><div class="row">${icon(b.kind==='regular'?'heart':b.kind==='room'?'room':'menu')}<h3>${esc(L(b.title))}</h3></div><p>${esc(L(b.description))}</p><p class="brief-hint">${esc(L(b.hint))}</p><p>${t('briefReward',{cash:cash(b.rewardCash)})}</p>${selected?.id===b.id?`<p class="pill gap-top">${icon('check')}${t(selected.completed?'briefCompleted':selected.ready?'briefReady':'briefInProgress')}</p>`:G.phase==='planning'?button('select-brief',t('chooseThisBrief'),'outline gap-top',`data-id="${esc(b.id)}" aria-label="${esc(t('chooseThisBrief')+' · '+L(b.title))}"`):''}</div>`).join('')}</div>${G.phase==='planning'&&selected?button('clear-brief',t('clearBrief'),'text-button wide','', 'close'):''}${G.phase!=='planning'?`<p class="description">${t('briefLockedPlan')}</p>`:''}${go('plan',t('plan'),'secondary gap-top','', 'menu')}</section>`;}
function briefOutcome(){const b=E.briefStatus?.(G);if(!b?.settled)return '';return `<div class="card gap-top"><div class="row">${icon(b.completed?'flag':'sun')}<h3>${esc(L(b.title))}</h3></div><p>${t(b.completed?'briefCompleteDesc':'briefAnotherDay')}</p>${b.completed?`<p class="brief-earned">+ ${cash(b.rewardEarned)}</p>${go('collection',t('seeKeepsakes'),'text-button start','', 'book')}`:''}</div>`;}
function collection(){return `<section class="padded">${back('legacy')}<div class="eyebrow">${t('familyBook')}</div><h1 class="title">${t('collectionTitle')}</h1><p class="description">${t('collectionDesc')}</p><div class="keepsake-grid gap-top">${E.BRIEF_STAMPS.map(stamp=>{const owned=G.keepsakes?.find(x=>x.kind===stamp.kind);return `<div class="card stamp ${owned?'earned':''}"><div class="stamp-symbol">${icon(owned?'flag':'spark')}</div><h3>${esc(L(stamp.name))}</h3><p>${esc(L(stamp.description))}</p><p class="small">${owned?t('stampCount',{count:num(owned.count)}):t('stampNotYet')}</p>${owned?`<p class="small">${date(owned.date,true)}</p>`:''}</div>`;}).join('')}</div>${go('briefs',t('chooseBrief'),'secondary gap-top','', 'flag')}</section>`;}
function library(){let list;try{list=P.list();}catch(_){return `<section class="padded">${back('settings')}<p>${t('libraryFailed')}</p>${go('export',t('export'),'secondary gap-top','', 'save')}</section>`;}return `<section class="padded">${back('settings')}<h1 class="title">${t('savedCafes')}</h1><p class="description">${t('savedCafesDesc')}</p>${button('keep-cafe',t('keepCafe'),'secondary gap-top','', 'save')}<div class="stack gap-top">${list.map(x=>`<button type="button" class="card choice" data-action="snapshot" data-id="${esc(x.id)}">${icon('cafe')}<span class="list-copy"><h3 dir="auto">${esc(x.name)}</h3><p>${esc(x.owner)} · ${date(x.date,true)}</p><p>${t('generation')} ${num(x.generation)}</p></span>${icon('arrow')}</button>`).join('')||`<p class="description">${t('noSavedCafes')}</p>`}</div>${go('newCafe',t('startAnotherCafe'),'text-button wide','', 'plus')}</section>`;}
function snapshotPage(){try{const x=E.importSave(P.snapshot(snapshotId));return `<section class="padded">${back('library')}<div class="eyebrow">${t('savedCafes')}</div><h1 class="title" dir="auto">${esc(x.cafeName)}</h1><p class="description">${esc(x.owner)} · ${date(x.date,true)}</p><div class="card gap-top"><p>${t('generation')} ${num(x.generation)}</p><p>${t('recipeCount',{count:num(E.allRecipes(x).length)})}</p><p>${cash(x.cash)}</p></div><p class="description">${t('openSavedDesc')}</p>${button('snapshot-export',t('export'),'secondary gap-top','', 'save')}${go('removeSnapshot',t('removeSavedCafe'),'text-button wide','', 'close')}</section>`;}catch(_){return library();}}
function removeSnapshotPage(){return `<section class="padded">${back('snapshot')}<h1 class="title">${t('removeSavedCafe')}</h1><p class="description">${t('removeSavedDesc')}</p></section>`;}
function newCafePage(){return `<section class="padded">${back('settings')}<div class="eyebrow">${t('newBeginning')}</div><h1 class="title">${t('startAnotherCafe')}</h1><p class="description">${t('newCafeDesc')}</p><label class="field"><span>${t('cafeName')}</span><input id="new-name" maxlength="40" value="${esc(t('defaultCafe'))}" dir="auto"></label><label class="field"><span>${t('ownerName')}</span><input id="new-owner" maxlength="40" value="${esc(t('defaultOwner'))}" dir="auto"></label><label class="field"><span>${t('origin')}</span><select id="new-origin">${['family','independent','partner'].map(x=>`<option value="${x}">${t(x)}</option>`).join('')}</select></label></section>`;}
function nativeRequest(type,details={}){const requestId='cafe-'+(++nativeCounter);nativePending.set(requestId,type);send({type,requestId,...details});}
function receiveImport(raw){try{const candidate=E.importSave(raw);importDraft=raw;page='import';notice=t('fileReady',{name:candidate.cafeName});render();}catch(_){notice=t('invalidSave');render();}}
window.addEventListener('cafe-native-result',event=>{const d=event.detail||{};if(nativePending.get(d.requestId)!==d.type)return;nativePending.delete(d.requestId);if(d.status==='selected'&&d.type==='pickSave'&&typeof d.text==='string'){receiveImport(d.text);return;}if(d.status==='error'){notice=t(d.error==='tooLarge'?'fileTooLarge':'fileError');render();}else if(d.status==='presented'){notice=t('exportOpened');render();}});
matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if(G?.settings.theme==='auto')render();});

window.CafeApp=Object.freeze({getState:()=>G?JSON.parse(JSON.stringify(G)):null,dispatch,start,render,exportSave:()=>G?E.exportSave(G):null});
lang=window.CAFE_NATIVE_LANGUAGE==='ar'||navigator.language?.startsWith('ar')?'ar':'en';load();render();
document.addEventListener('visibilitychange',()=>{if(document.hidden){persist();A?.stop();}else if(G)A?.resume();});window.addEventListener('pagehide',()=>{persist();A?.stop();});
})();
