// Arena calibration.
//
// Run: node tools/calibrate.mjs [samplesPerProbe] [--write]
//
// Twenty-five arenas cannot be hand-tuned one at a time and stay consistent.
// Forward drive is monotone in goals-per-match, so one binary search per arena
// lands every one of them on the scoring rate its design calls for. With
// --write the result is baked into src/sim/tuning.js.
//
// Drive is a property of the ARENA. It applies identically to both marbles and
// is not, and can never be, a property of a nation.

import { writeFileSync } from 'node:fs';
import { simulate } from '../src/sim/match.js';
import { ARENA_META, ARENA_IDS, designTension } from '../src/sim/arenas.js';
import { TARGETS, DRIVE } from '../src/sim/tuning.js';
import { STEP } from '../src/core/physics.js';

const N = Number(process.argv[2] || 220);
const WRITE = process.argv.includes('--write');
// --only=id re-tunes a single arena after a design change, instead of all 25.
const ONLY = (process.argv.find(a => a.startsWith('--only=')) || '').slice(7);
const RULES = { allowDraw: true, extraTime: false };

function measure(arenaId, drive, n, seed0) {
  let goals = 0, ticks = 0, maxTicks = 0;
  for (let i = 0; i < n; i++) {
    const r = simulate({
      teams: ['A', 'B'], arenaId, tension: designTension(arenaId),
      seed: (seed0 + i * 2654435761) >>> 0, rules: RULES, drive,
    });
    goals += r.score[0] + r.score[1];
    ticks += r.ticks;
    if (r.ticks > maxTicks) maxTicks = r.ticks;
  }
  return { goals: goals / n, mean: ticks / n * STEP, max: maxTicks * STEP };
}

const out = { ...DRIVE };
const rows = [];
const todo = ONLY ? ARENA_IDS.filter(id => id === ONLY) : ARENA_IDS;
console.log(`\nCalibrating ${todo.length} arena${todo.length === 1 ? '' : 's'} (${N} matches per probe)\n`);

for (const id of todo) {
  const target = TARGETS[id] ?? 2.6;
  let lo = 1, hi = 70, best = null;
  // Ten bisections is ample: drive resolution below ~0.1 does not move the mean.
  for (let it = 0; it < 10; it++) {
    const mid = (lo + hi) / 2;
    const m = measure(id, mid, N, 11 + id.length * 977);
    if (!best || Math.abs(m.goals - target) < Math.abs(best.goals - target)) best = { drive: mid, ...m };
    if (m.goals < target) lo = mid; else hi = mid;
  }
  const drive = Math.round(best.drive * 10) / 10;
  const check = measure(id, drive, N * 2, 999331 + id.length * 31);
  out[id] = drive;
  rows.push({
    arena: ARENA_META[id].name, tier: ARENA_META[id].tier, drive,
    target, goals: check.goals.toFixed(2),
    mean_s: check.mean.toFixed(1), max_s: check.max.toFixed(1),
    off: (check.goals - target).toFixed(2),
  });
  console.log(`  ${ARENA_META[id].name.padEnd(18)} drive ${String(drive).padStart(5)}  goals ${check.goals.toFixed(2)} (target ${target})  ${check.mean.toFixed(1)}s mean, ${check.max.toFixed(1)}s max`);
}

console.table(rows);

const far = rows.filter(r => Math.abs(Number(r.off)) > 0.35);
if (far.length) {
  console.log('\nArenas that could not reach their target by drive alone (need a design change):');
  for (const r of far) console.log(`  ${r.arena}: ${r.goals} vs target ${r.target}`);
}
const slow = rows.filter(r => Number(r.max_s) > 60);
if (slow.length) {
  console.log('\nArenas running past 60s:');
  for (const r of slow) console.log(`  ${r.arena}: ${r.max_s}s`);
}

if (WRITE) {
  const entries = ARENA_IDS.map(id => `  ${id}: ${out[id]},`).join('\n');
  const targets = ARENA_IDS.map(id => `  ${id}: ${TARGETS[id] ?? 2.6},`).join('\n');
  writeFileSync(new URL('../src/sim/tuning.js', import.meta.url), `// Per-arena forward drive.
//
// GENERATED by tools/calibrate.mjs -- run that, do not edit DRIVE by hand.
//
// Drive is the single knob that sets how hard each marble pushes toward the end
// it is attacking, and it is monotone in goals-per-match, so one binary search
// per arena is enough to land all twenty-five on their target scoring rates.
//
// Nothing here is per-nation. Drive is a property of the arena and applies
// identically to both marbles.

export const DRIVE = {
${entries}
};

// Goals per match each arena aims for. Variety is deliberate: a cagey 2.0-goal
// final and a 3.0-goal shoot-out are both football.
export const TARGETS = {
${targets}
};
`);
  console.log('\nWrote src/sim/tuning.js');
}
