#!/usr/bin/env python3
"""Compose brand/guidelines.html -- the Cafe Rush brand guidelines, 297x210mm landscape.

Colour pages are generated from assets/colour/tokens.json so the book can never
disagree with the stylesheet a developer imports. Copy is quoted from strategy.md.
Render to PDF with brand/render-guidelines.js.
"""
import json, pathlib, html as H

ROOT = pathlib.Path(__file__).resolve().parent
TOK = json.loads((ROOT / "assets" / "colour" / "tokens.json").read_text())
BY = {t["token"]: t for g in TOK["groups"] for t in g["tokens"]}
GROUP = {g["key"]: g for g in TOK["groups"]}

DISHES = ["espresso", "cortado", "latte", "iced", "karak", "saffron", "affogato",
          "dateshake", "luqaimat", "regag", "datepaste", "almond"]
ING = ["shot", "milk", "tea", "syrup", "pastry", "dough", "ice", "mint"]
MACH = ["m_espresso", "m_steamer", "m_kettle", "m_oven", "m_syrup", "m_ice"]
PORT = ["p1", "p3", "p5", "p7", "p9", "p11"]


# ---------------------------------------------------------------- doc assets
# Chromium embeds every image at source resolution, which took the first PDF to
# 32 MB for a 29-page book. Sprites print at 50 px and room plates at 230 px, so
# the document gets its own downscaled copies rather than the 512 and 1672 masters.
def doc_assets():
    from PIL import Image
    src = ROOT.parent / "art" / "sprites"
    out = ROOT / "doc-assets"; out.mkdir(exist_ok=True)
    plan = [(n, 128) for n in DISHES + ING + MACH + PORT]
    plan += [("karak", 512), ("luqaimat", 512), ("latte", 512)]      # cover, at 340 px
    seen = set()
    for name, w in plan:
        dst = out / ("%s-%d.png" % (name, w))
        if dst.name in seen:
            continue
        seen.add(dst.name)
        im = Image.open(src / (name + ".png")).convert("RGBA")
        if im.width > w:
            im = im.resize((w, round(im.height * w / im.width)), Image.LANCZOS)
        im.save(dst, optimize=True)

    # opaque images carry no alpha to preserve, and a flate PNG of a photographic
    # plate is four times the size of a JPEG that prints identically at 230 px
    flat = [(src / "room_day.png", "room_day", 560), (src / "room_evening.png", "room_evening", 560),
            (src / "room_counter.png", "room_counter", 560),
            (src / "room_evening.png", "room_evening", 1400),
            (ROOT / "assets/marketing/play-feature-1024x500.png", "mk-feature", 1024),
            (ROOT / "assets/marketing/social-banner-1200x630.png", "mk-social", 1200)]
    for path, name, w in flat:
        im = Image.open(path).convert("RGB")
        if im.width > w:
            im = im.resize((w, round(im.height * w / im.width)), Image.LANCZOS)
        im.save(out / ("%s-%d.jpg" % (name, w)), quality=88, optimize=True, progressive=True)
        seen.add(name)
    return len(seen)

def sp(name, w):
    return "doc-assets/%s-%d.png" % (name, w)

print("doc-assets: %d images" % doc_assets())

pages = []
def page(kind, section, title, body, dark=False):
    pages.append((kind, section, title, body, dark))

def e(s): return H.escape(s)

# ---------------------------------------------------------------- cover
page("cover", "", "", """
  <img class="cv-plate" src="doc-assets/room_evening-1400.jpg" alt="">
  <div class="cv-scrim"></div>
  <img class="cv-food a" src="doc-assets/karak-512.png" alt="">
  <img class="cv-food b" src="doc-assets/luqaimat-512.png" alt="">
  <img class="cv-food c" src="doc-assets/latte-512.png" alt="">
  <div class="cv-copy">
    <div class="wm cv-wm">Caf<i>&eacute;</i> Rush</div>
    <div class="cv-sub">Brand guidelines</div>
    <div class="cv-meta">
      <span>Version 1.0</span><span>16 September 2026</span><span>Amber on ink</span>
    </div>
  </div>
  <div class="cv-foot">A ninety-second cooking rush you buy once and own forever.</div>
""", dark=True)

# ---------------------------------------------------------------- how to use
page("std", "00", "How to use this document", """
<div class="two">
  <div>
    <p class="lede">This book governs every word and every colour that leaves the project with
    the name Caf&eacute; Rush on it. It is a set of vetoes, not a mood board.</p>
    <p>Where a page here conflicts with a marketing instinct, this book wins. Where it
    conflicts with <code>docs/design-spec.md</code>, <code>docs/requirements.md</code>,
    <code>docs/target-player.md</code>, <code>docs/art-plan.md</code> or
    <code>docs/rush-pivot.md</code>, those documents win and this book is wrong and must be
    amended. That has already happened once: rule&nbsp;23 originally banned the generated
    painted art the game actually ships, and was corrected rather than quietly ignored.</p>
    <p>The colour pages are generated from <code>assets/colour/tokens.json</code> by
    <code>build-tokens.py</code>, and this document is generated by
    <code>build-guidelines.py</code>. Nothing in either is typed by hand twice, so the book
    and the stylesheet a developer imports cannot drift apart.</p>
  </div>
  <div>
    <div class="callout">
      <div class="callout-h">The one rule under all the others</div>
      <p>A hex value that is not a token is a bug. A sentence with an exclamation mark in it
      is a bug. A second thing for sale is a breach of contract with the player.</p>
    </div>
    <div class="toc">
      <div class="toc-h">Contents</div>
      <ol>
        <li><span>The promise</span></li>
        <li><span>Positioning</span></li>
        <li><span>Who this is for</span></li>
        <li><span>What we stand against</span></li>
        <li><span>Personality</span></li>
        <li><span>Voice and tone</span></li>
        <li><span>The name</span></li>
        <li><span>Logo</span></li>
        <li><span>App icon</span></li>
        <li><span>Colour</span></li>
        <li><span>Typography</span></li>
        <li><span>Art direction</span></li>
        <li><span>Marketing</span></li>
        <li><span>Store listing</span></li>
        <li><span>The rules</span></li>
      </ol>
    </div>
  </div>
</div>
""")

# ---------------------------------------------------------------- 01 promise
page("std", "01", "The promise", """
<div class="promise-hero">
  <div class="big">A ninety-second cooking rush<br>you buy once and own forever.</div>
</div>
<div class="three">
  <div><div class="k">Ninety-second cooking rush</div>
    <p>Tells a genre-literate player exactly what this is &mdash; seats filling, patience
    draining, machines running on their own timers behind you. Nobody arrives expecting a
    calm farming sim and leaves a one-star review saying so.</p></div>
  <div><div class="k">Buy once</div>
    <p>The whole commercial model in two words: a free first chapter, then one payment of
    AED&nbsp;24.99, and nothing else is ever for sale.</p></div>
  <div><div class="k">Own forever</div>
    <p>The longevity claim and the anti-FOMO claim at once. Thirty days, ninety stars and an
    Endless Rush that does not end &mdash; none of it expiring, none of it requiring you to
    show up on a Tuesday.</p></div>
</div>
<div class="rules-out">
  <div class="rules-out-h">It rules out three things we will be tempted by</div>
  <div class="three tight">
    <p><b>Calling this cozy.</b> The player liked the fast one. Mis-selling the pace puts the
    game in front of exactly the wrong audience.</p>
    <p><b>A second purchase.</b> "Once" and "forever" are the promise, and the first expiring
    offer makes us liars.</p>
    <p><b>Selling on production value.</b> The promise is about the deal and the loop, not
    about how the croissant is painted.</p>
  </div>
</div>
""")

# ---------------------------------------------------------------- 02 positioning
page("std", "02", "Positioning", """
<div class="two wide-left">
  <div>
    <blockquote class="pos">For the <b>lapsed Dash player</b> who finished the cooking games
    they loved and was disappointed that they ended, Caf&eacute; Rush is the <b>premium
    time-management game</b> that gives you <b>the whole rush</b> &mdash; thirty days, twelve
    recipes and an endless shift &mdash; <b>for one payment</b>, unlike Cooking Fever,
    Cooking Madness and every frenzy clone whose pacing exists to sell gems, <b>because a
    shift tuned to be fair pays for itself at AED&nbsp;24.99 and a shift tuned to be
    frustrating pays for itself in gems.</b></blockquote>
  </div>
  <div class="defs">
    <div><div class="k">For the lapsed Dash player</div>
      <p>Not "casual mobile gamers". A specific person who played the Dash series, liked it,
      and whose loudest complaint was that it was finished pretty fast. We position against
      that disappointment, not against a demographic.</p></div>
    <div><div class="k">The premium time-management game</div>
      <p>Not "cooking game", a shelf so crowded the word carries no meaning. Not "cozy",
      a genre this product is not in. Premium is load-bearing: the price model is the
      differentiator.</p></div>
    <div><div class="k">Because the incentives differ</div>
      <p>The reason clause is a business fact, not a claim about our character. We took the
      money up front, so we have no reason to make day nineteen unfair.</p></div>
  </div>
</div>
""")

# ---------------------------------------------------------------- 03 who
page("std", "03", "Who this is for", """
<div class="two wide-left bio">
  <div>
    <p class="lede">She has a phone full of games she has stopped opening. She liked Diner
    Dash &mdash; genuinely liked it, played it properly, got fast at it &mdash; and when it
    ended she went looking for the next one and found a wall of games that looked the same
    and behaved completely differently.</p>
    <p>One made her wait four hours for a kitchen to be built. One sold a gem-purchased speed
    boost that was the only way to clear level thirty-one. One wanted her to ask three friends
    for a key. Two played a thirty-second unskippable video between shifts. She uninstalled
    all of them, and what she wrote afterwards was not a rant about capitalism. It was a
    request: <b>something in this genre, that lasts a while, that does not require her to
    show up.</b></p>
    <p>She plays a few hours a week. Sometimes a fortnight passes, and she needs that to cost
    her nothing &mdash; no broken streak, no expired event, no withered crops. She will pay,
    and she framed it the way most people do: a few dollars, to make the ads go away. She is
    worth exactly one purchase, and the business depends on that purchase being good enough
    that she buys the next game too.</p>
    <p class="hot"><b>She is fast.</b> This matters more than anything else on this page and
    it is the thing we will most often get wrong. She wants overlapping timers, a full
    counter, a customer going red at seat three while the dough is still four seconds out.
    She did not reject the pace. She rejected the scaffolding bolted to it.</p>
  </div>
  <div>
    <div class="callout neg">
      <div class="callout-h">She is not</div>
      <ul class="ticks">
        <li>A cozy-game player who wants a gentle evening &mdash; she asked for the Dash games by name.</li>
        <li>A completionist who will grind ninety stars out of obligation. She will grind them because the run is good.</li>
        <li>A whale, a subscriber, a daily-active-user, a retention cohort or a funnel.</li>
        <li>A child.</li>
        <li>A lapsed player we get to win back with a notification.</li>
        <li>Waiting for us. If day nineteen is unfair or day six ends in a pop-up, she closes the app and never thinks about it again.</li>
      </ul>
    </div>
  </div>
</div>
""")

# ---------------------------------------------------------------- 04 against
AGAINST = [
 ("Energy, stamina and lives", "A ninety-second shift behind a four-hour meter is the specific insult that started this project. Any shift replays immediately, forever."),
 ("Build queues and real-time waits", "Every upgrade applies the instant it is bought. Nothing completes in 2h."),
 ("Premium currency", "One currency, AED, earned by playing. It cannot be bought, gifted, topped up or traded."),
 ("Paywalled difficulty", "No purchase, ad, consumable or boost may make a shift easier, extend a timer, skip a day or raise earnings."),
 ("Paywalled accessibility", "Relaxed Timing is free, always available, and earns full stars and full progression."),
 ("Social gating", "No invites, no keys from friends, no guild requirement, no share-to-continue."),
 ("Ads", "Not interstitial, not banner, not rewarded, not &ldquo;optional&rdquo; rewarded. The binary contains no ad SDK."),
 ("Daily rewards and expiring content", "Anything earnable today is earnable in six months, identically."),
 ("Notifications that ask her back", "Off by default. The only permitted notification is a local reminder she set herself."),
 ("Discount countdowns", "The price is the price."),
]
page("std", "04", "What we stand against", """
<p class="lede">Caf&eacute; Rush refuses, permanently and in the shipped binary:</p>
<div class="against">%s</div>
<div class="rules-out">
  <div class="rules-out-h">Why the refusal is the brand, and not a feature list</div>
  <p class="wide">Every one of those patterns is individually profitable, and a brand is only
  what you turn down when it costs you something. A feature list is a set of things we built.
  This is a set of things we were offered and declined &mdash; a rewarded-ad button is perhaps
  three days of work and a measurable revenue line, and we will not ship it in year four
  either. The player cannot verify our intentions, but she can verify a binary with no ad SDK
  in it, and she can verify that the store page still says one purchase eighteen months after
  launch. That verifiability is the asset. It is fragile in exactly one direction: it survives
  a bad review, and it does not survive us doing it once.</p>
</div>
""" % "".join('<div class="ag"><div class="ag-x">&#10007;</div><div><b>%s</b><span>%s</span></div></div>' % (t, d) for t, d in AGAINST))

# ---------------------------------------------------------------- 05 personality
PERS = [
 ("Fast", "The product&rsquo;s first quality: overlapping timers, a counter that fills, ninety seconds that feel shorter than ninety seconds. Everything we make should move at that pace, including the sentences.", "frantic", "Frantic is chaos the player cannot read. Fast is chaos the player can read and is only just keeping up with."),
 ("Plain", "We say the number, the price, the recipe and the reason. A hint tells you what to do; a failure card tells you what happened.", "blunt", "Blunt is telling a player they were too slow. Plain is telling them the dough takes five seconds."),
 ("Warm", "The caf&eacute; is lamp-lit at dusk, the palette is amber on ink, and the street outside is a real place with karak and luqaimat on it. Warmth is in the light and the food, never in the tone of voice.", "cozy", "Cozy is a promise of no pressure, and this game is made of pressure. We are warm and difficult at once, which is what a good kitchen is."),
 ("Specific", "Regag rolls, not &ldquo;flatbread snack&rdquo;. Saffron karak, not &ldquo;premium tea&rdquo;. Ninety seconds, not &ldquo;fast-paced action&rdquo;. AED 24.99, not &ldquo;affordable&rdquo;.", "exotic", "We are not presenting the UAE as a setting to be marvelled at; it is simply where the shop is, and a regag roll needs no more explanation than a croissant."),
 ("Honest", "We state what the game does not do &mdash; no in-shift screen-reader support in v1.0, thirty days and then Endless, thirty minutes free. Naming our limits is the same instinct that made us name our refusals.", "humble", "We are not apologising for the scope. We chose it, and we will defend it."),
]
page("std", "05", "Personality", """
<div class="pers">%s</div>
""" % "".join(
 '<div class="pv"><div class="pv-h">%s</div><p>%s</p>'
 '<div class="pv-c"><span class="pv-l">Often confused with</span> <b>%s</b><p>%s</p></div></div>'
 % (n, d, c, cd) for n, d, c, cd in PERS))

# ---------------------------------------------------------------- 06 voice rules
VOICE = [
 ("British English, sentence case", "Oxford comma off. Serial commas only where meaning requires them."),
 ("Second person, present tense", "&ldquo;You hold the milk&rdquo;, not &ldquo;players can hold milk&rdquo;."),
 ("No exclamation marks", "In any player-facing string, including result cards and purchase confirmations. The excitement is in the clock, not the punctuation."),
 ("No hype adjectives", "Amazing, epic, ultimate, addictive, insane, crazy, satisfying, relaxing and stunning are banned. If a line survives their deletion, it did not need them."),
 ("Numbers are real and specific", "90 seconds, 30 days, 12 recipes, 8 machines, AED 24.99. Never &ldquo;hundreds of levels&rdquo;, never a number we have not counted."),
 ("Never imply urgency the game does not have", "No &ldquo;now&rdquo;, &ldquo;today&rdquo;, &ldquo;don&rsquo;t miss&rdquo;, &ldquo;limited&rdquo;, &ldquo;hurry&rdquo;. The only clock runs inside a shift."),
 ("Failure copy is diagnostic", "Name what happened, in the player&rsquo;s own run, in one line. Never scold, never console, never say &ldquo;oops&rdquo;."),
 ("Never ask the player to come back", "In any channel, ever."),
 ("Local words stand on their own", "Karak, luqaimat, regag, istikana. Glossed exactly once in the recipe list; never glossed again, never italicised, never in quotes."),
 ("Length", "UI lines are twelve words or fewer. Store paragraphs are four sentences or fewer. Hints are one sentence."),
 ("ALL CAPS is a typographic style, not a voice", "Only the 9&nbsp;pt label style is uppercase &mdash; DAY, EARNED, TARGET, STREAK. Nothing else shouts."),
 ("Arabic is the voice in Arabic", "Not a translation of it. Dish names use the local term &mdash; &#1603;&#1585;&#1603;, &#1604;&#1602;&#1610;&#1605;&#1575;&#1578;, &#1585;&#1602;&#1575;&#1602; &mdash; reviewed by a Gulf-Arabic speaker. The Arabic build is never the afterthought build."),
]
page("std", "06", "Voice and tone", """
<div class="voice">%s</div>
""" % "".join('<div class="vr"><span class="n">%d</span><div><b>%s</b><span>%s</span></div></div>'
              % (i + 1, t, d) for i, (t, d) in enumerate(VOICE)))

# ---------------------------------------------------------------- 06b before/after
BA = [
 ("Store listing, opening line", "Get ready for the ultimate cooking adventure! Serve delicious dishes to hungry customers in this addictive time-management game!", "Ninety seconds. Five seats. The dough takes five of those seconds, so you start it before anyone orders it."),
 ("In-game hint", "Tip: Try to plan ahead and be efficient with your time to maximise your score!", "Pastry takes 4.0 seconds. Start it before the order lands."),
 ("Failure message", "Oh no! You failed! Better luck next time &mdash; why not try again?", "Day 9 &middot; AED 640 of 780. Four customers walked out at seat 2 while the plate was full."),
 ("Upgrade description", "Supercharge your caf&eacute; with lightning-fast machines and watch your profits soar!", "Bigger bins &mdash; the tea machine holds 5 instead of 3. Cook two ahead during a quiet stretch."),
 ("Push notification", "&#9749; Your customers miss you! Come back and claim your daily bonus before it expires!", "Reminder you set for Sundays at 19:00. Caf&eacute; Rush is where you left it."),
 ("Error", "Something went wrong :( Please try again later.", "The App Store did not respond. Your progress is saved on this phone. Try Restore Purchases in Settings."),
]
BA2 = [
 ("Tutorial step", "Tap the glowing button to cook a shot! Great job! You&rsquo;re a natural!", "Tap Shot to start one. It takes 2.2 seconds and waits in the bin until you need it."),
 ("Thank-you after purchase", "Thank you for your purchase! Enjoy your amazing new content and happy cooking!", "Bought. Days 7 to 30 are open, Endless Rush is unlocked, and that was the only purchase in this game."),
 ("Paywall card, day 6", "Unlock the FULL experience! Limited-time launch price &mdash; don&rsquo;t miss out!", "That was chapter one. AED 24.99 opens the other 24 days, 6 recipes, 2 machines and Endless Rush. One payment. No ads, no currency, nothing else to buy."),
 ("Endless Rush result", "WOW! Incredible run! Can you beat your friends&rsquo; scores?", "Wave 14. Personal best was wave 12. Three walked out in the last forty seconds."),
 ("Settings, analytics toggle", "Help us improve your experience by sharing anonymous usage data!", "Send anonymous play data. Off by default. Nothing identifying, no advertising, and the game works identically either way."),
 ("Recipe list entry", "Saffron Karak &mdash; a luxurious and exotic Middle Eastern tea experience!", "Saffron karak &mdash; tea, milk, syrup, date paste. AED 34. Nine taps, the longest order on the menu."),
]
def ba_table(rows):
    head = ('<div class="ba"><div class="ba-r ba-head"><div>Context</div>'
            '<div class="w">Wrong</div><div class="r">Right</div></div>')
    body = "".join('<div class="ba-r"><div class="ctx">%s</div><div class="w">%s</div>'
                   '<div class="r">%s</div></div>' % r for r in rows)
    return head + body + "</div>"
page("std", "06", "Voice &mdash; before and after", ba_table(BA + BA2) + """
<p class="foot-note">The right-hand column is not a nicer version of the left. It is the same
information with the selling removed, which is why it is shorter every time.</p>
""")

# ---------------------------------------------------------------- 07 name
page("std", "07", "The name", """
<div class="two wide-left">
  <div>
    <div class="verdict">Keep Caf&eacute; Rush. The subtitle carries the load.</div>
    <div class="three tight">
      <div><div class="k">What it gets right</div>
        <p>Two words, five syllables, and both halves work. <i>Caf&eacute;</i> places the
        setting and signals food without claiming a cuisine, which matters when the menu is
        karak and luqaimat. <i>Rush</i> is the honest word for the loop, and the name should
        not quietly re-open the argument that pivot settled. It is pronounceable in Arabic and
        English, short enough for a 48&nbsp;dp icon at two lines, and sits well in the
        display face.</p></div>
      <div><div class="k">What it risks</div>
        <p>Genre crowding is real: <i>rush</i>, <i>dash</i>, <i>fever</i>, <i>frenzy</i> and
        <i>madness</i> are the standard vocabulary of this shelf. Searchability is the sharper
        problem &mdash; nobody searches for a name they have never heard, so the name
        contributes almost nothing to discovery on its own.</p></div>
      <div><div class="k">Why we keep it</div>
        <p>A distinctive name nobody searches is a worse problem than a familiar name in a
        crowded field, because the name is not the discovery mechanism &mdash; the subtitle,
        the keywords and the screenshots are. Our differentiator is the price model, and that
        goes in the subtitle where it is indexed and read.</p></div>
    </div>
    <div class="callout">
      <div class="callout-h">What the subtitle must do, in this order</div>
      <p>State the commercial model, because it is the only thing about this product a
      competitor&rsquo;s listing cannot also claim. Carry the anti-brand in words a scanning
      player recognises from their own frustration. Say nothing about quality, because every
      listing says that and none of it is read. It must not describe the gameplay, and it must
      not contain an adjective.</p>
    </div>
  </div>
  <div>
    <div class="strings">
      <div class="str"><span class="str-l">App Store title &mdash; 23 of 30</span>
        <code>Caf&eacute; Rush: Cooking Game</code></div>
      <div class="str"><span class="str-l">App Store subtitle &mdash; 29 of 30</span>
        <code>No ads. No timers. One price.</code></div>
    </div>
    <p class="small">The word &ldquo;Cooking&rdquo; is in the title for one reason: the title
    field is a search index, not a headline. The subtitle is the headline, and it is the only
    line in this book permitted to sell by negation.</p>
    <div class="e-note">
      <div class="e-big">Caf<i>&eacute;</i></div>
      <p>The accent is kept. Store search normalises diacritics, &ldquo;Cafe Rush&rdquo; looks
      like a typo, and the &eacute; is a quiet promise that the details were attended to. It
      is set in <code>amber-500</code> in the wordmark, and in plain type everywhere else.</p>
    </div>
  </div>
</div>
""")

# ---------------------------------------------------------------- 08 logo
page("std", "08", "Logo", """
<div class="logo-hero"><img src="assets/logo/wm-dark.png" alt=""></div>
<div class="four">
  <div class="spec"><img src="assets/logo/wm-light.png" alt="">
    <div class="sp-l">On paper</div><p>Amber becomes <code>amber-700</code>. The lighter
    amber does not hold at text weight on a light ground.</p></div>
  <div class="spec"><img src="assets/logo/wm-stack.png" alt="">
    <div class="sp-l">Stacked</div><p>For square and near-square spaces. Line break after
    Caf&eacute;, never a hyphen, never three lines.</p></div>
  <div class="spec"><img src="assets/logo/lockup-dark.png" alt="">
    <div class="sp-l">Lockup</div><p>Icon at cap height beside the mark, on one optical
    baseline. Gap is one-fifth of the icon width.</p></div>
  <div class="spec"><img src="assets/logo/wm-mono-dark.png" alt="">
    <div class="sp-l">Mono</div><p>One-colour reproduction only: embroidery, engraving, a
    single-ink print. Never used when colour is available.</p></div>
</div>
<div class="specs-row">
  <div><span class="k">Face</span> Bricolage Grotesque 800</div>
  <div><span class="k">Tracking</span> &minus;0.045em</div>
  <div><span class="k">The &eacute;</span> <code>amber-500</code> on ink, <code>amber-700</code> on paper</div>
  <div><span class="k">Clearspace</span> the cap height of the R, on all four sides</div>
  <div><span class="k">Minimum width</span> 96&nbsp;px screen, 24&nbsp;mm print</div>
</div>
""")

# ---------------------------------------------------------------- 08b misuse
page("std", "08", "Logo &mdash; misuse", """
<p class="lede">The wordmark is never all-caps, never letter-spaced, never outlined, never
stretched, never gradiented, never shadowed, and never placed on a ground other than
<code>ink-900</code>, <code>ink-950</code> or <code>paper-100</code>. The one permitted
effect is a <code>sun-300</code> glow behind it on key art, at 12% or less.</p>
<div class="misuse">
  <div class="mu"><div class="mu-box"><span class="wm mu-wm" style="text-transform:uppercase">CAF&Eacute; RUSH</span></div><div class="mu-c">Never all-caps</div></div>
  <div class="mu"><div class="mu-box"><span class="wm mu-wm" style="letter-spacing:.14em">Caf<i>&eacute;</i> Rush</span></div><div class="mu-c">Never letter-spaced</div></div>
  <div class="mu"><div class="mu-box"><span class="wm mu-wm" style="transform:scaleX(1.3);display:inline-block">Caf<i>&eacute;</i> Rush</span></div><div class="mu-c">Never stretched</div></div>
  <div class="mu"><div class="mu-box"><span class="wm mu-wm" style="background:linear-gradient(90deg,#F2A03D,#E24B2E);-webkit-background-clip:text;color:transparent">Caf&eacute; Rush</span></div><div class="mu-c">Never gradiented</div></div>
  <div class="mu"><div class="mu-box"><span class="wm mu-wm" style="text-shadow:0 6px 0 #0E0B09,0 0 18px rgba(242,160,61,.9)">Caf<i>&eacute;</i> Rush</span></div><div class="mu-c">Never shadowed or glowing</div></div>
  <div class="mu"><div class="mu-box" style="background:#3E6E6B"><span class="wm mu-wm">Caf<i>&eacute;</i> Rush</span></div><div class="mu-c">Never on a coloured ground</div></div>
  <div class="mu"><div class="mu-box"><span class="wm mu-wm" style="-webkit-text-stroke:2px #E8C36B;color:transparent">Caf&eacute; Rush</span></div><div class="mu-c">Never outlined</div></div>
  <div class="mu"><div class="mu-box"><span class="wm mu-wm" style="font-family:'DM Sans',sans-serif;font-weight:700">Caf&eacute; Rush</span></div><div class="mu-c">Never reset in another face</div></div>
</div>
""")

# ---------------------------------------------------------------- 09 icon
page("std", "09", "App icon", """
<div class="icon-page">
  <div class="icon-hero">
    <img src="assets/icon/web/icon-512.png" alt="">
    <div>
      <p class="lede">One istikana glass of karak, lit from the left, on <code>ink-900</code>
      with the counter falling away behind it. No wordmark, no character, no badge.</p>
      <p>The icon is read at 48&nbsp;dp in a grid of sixty others, which is why it carries one
      object and one light source. The glass is the most recognisable silhouette on the menu
      and the only one that is unmistakably this street rather than any caf&eacute;.</p>
      <p>The Android adaptive pair inset the artwork to a 66% safe zone and sit it on a flat
      <code>#AB5C1D</code> background sampled from the icon itself, because the launcher may
      crop to a circle, a squircle or a rounded square and we do not get to choose which.</p>
    </div>
  </div>
  <div class="icon-sizes">
    <div class="ic"><img src="assets/icon/ios/icon-180.png" style="width:90px"><span>180</span></div>
    <div class="ic"><img src="assets/icon/ios/icon-120.png" style="width:60px"><span>120</span></div>
    <div class="ic"><img src="assets/icon/ios/icon-87.png" style="width:44px"><span>87</span></div>
    <div class="ic"><img src="assets/icon/ios/icon-58.png" style="width:29px"><span>58</span></div>
    <div class="ic"><img src="assets/icon/ios/icon-40.png" style="width:20px"><span>40</span></div>
    <div class="ic"><img src="assets/icon/ios/icon-29.png" style="width:15px"><span>29</span></div>
    <div class="ic sep"><img src="assets/icon/android/adaptive-foreground-432.png" style="width:90px"><span>adaptive fg</span></div>
    <div class="ic"><img src="assets/icon/android/adaptive-background-432.png" style="width:90px"><span>adaptive bg</span></div>
  </div>
  <p class="foot-note">33 files ship: 18 iOS, 10 Android including the adaptive pair and the
  Play 512, and 5 for web and favicon use. Never re-derive one by scaling another in a
  document &mdash; every size is exported from the 1024 master.</p>
</div>
""")

# ---------------------------------------------------------------- 10 colour
def swatch_rows(keys, klass=""):
    out = []
    for k in keys:
        t = BY[k]
        out.append(
          '<div class="sw %s"><div class="sw-chip" style="background:%s"></div>'
          '<div class="sw-b"><div class="sw-t">%s<span class="sw-hex">%s</span></div>'
          '<div class="sw-u">%s</div>%s'
          '<div class="sw-cr">on ink-900 <b>%.1f:1</b> &nbsp;&middot;&nbsp; on paper-100 <b>%.1f:1</b></div>'
          '</div></div>'
          % (klass, t["hex"], t["token"], t["hex"], t["use"],
             ('<div class="sw-n"><span>never</span>%s</div>' % t["never"]) if t["never"] else "",
             t["onInk900"], t["onPaper100"]))
    return "".join(out)

page("std", "10", "Colour &mdash; the brand is amber on ink", """
<div class="two even">
  <div><div class="grp-h">Primary</div>%s</div>
  <div><div class="grp-h">Secondary &mdash; the street</div>%s</div>
</div>
""" % (swatch_rows(["ink-900", "amber-500", "amber-400", "amber-700", "ink-950"]),
       swatch_rows(["terracotta-600", "terracotta-400", "brass-400", "tile-500", "sun-300"])))

page("std", "10", "Colour &mdash; surface, type and state", """
<div class="two even">
  <div><div class="grp-h">Surfaces and edges</div>%s
    <p class="small">Never more than three surface steps in one composition, in a slide as much
    as in a scene file.</p></div>
  <div><div class="grp-h">Type, paper and the outline</div>%s</div>
</div>
""" % (swatch_rows(["ink-850", "ink-800", "ink-700", "ink-600", "ink-500", "ink-450"], "compact"),
       swatch_rows(["cream-50", "cream-200", "cream-400", "cream-600", "paper-100", "ink-outline"], "compact")))

page("std", "10", "Colour &mdash; semantic state", """
<p class="lede">These are learned in the first shift and must mean the same thing everywhere,
including in a screenshot on a store page.</p>
<div class="two even">
  <div>%s</div>
  <div>
    <div class="callout">
      <div class="callout-h">Why blue &rarr; amber &rarr; red, and never green &rarr; red</div>
      <p>Patience runs from <code>state-calm</code> blue through <code>state-soon</code> amber
      to <code>state-urgent</code> red. Green is never a patience colour, because roughly one
      man in twelve cannot separate it from red, and because green in this product means one
      thing only: money earned and target met.</p>
    </div>
    <div class="ramp">
      <div class="ramp-h">Patience, full to empty</div>
      <div class="ramp-bar"></div>
      <div class="ramp-l"><span>100%%</span><span>55%%</span><span>25%%</span><span>0</span></div>
    </div>
    <div class="callout neg">
      <div class="callout-h">The two absolutes</div>
      <p><code>brass-400</code> is money and nothing else. <code>ok-500</code> is money earned
      and target met and nothing else. The rule is absolute because the player learns it in
      ninety seconds, and a single decorative use un-teaches it.</p>
    </div>
  </div>
</div>
""" % swatch_rows(["state-calm", "state-soon", "state-urgent", "ok-500", "focus-500"]))

# ---------------------------------------------------------------- 10d fills
fills = "".join(
  '<div class="fl"><div class="fl-pair"><span style="background:%s"></span>'
  '<span style="background:%s"></span></div><b>%s</b><i>%s &middot; %s</i></div>'
  % (f["hex"], f["shade"], f["token"], f["hex"], f["shade"]) for f in TOK["fills"])
acc = "".join('<div class="af"><span style="background:%s"></span><b>%s</b><i>%s</i></div>'
              % (a["hex"], a["token"].replace("fill-", ""), a["hex"]) for a in TOK["accentFills"])
chips = "".join('<span class="chip" style="background:%s"></span>' % c for c in TOK["customerChips"])
page("std", "10", "Colour &mdash; art fills and identity", """
<div class="two even">
  <div>
    <div class="grp-h">Light Fill set</div>
    <p class="small">The only fills permitted to dominate a sprite&rsquo;s silhouette. All are
    L*&nbsp;&ge;&nbsp;70 and separate cleanly from <code>ink-900</code>. Each ships with its
    shade partner, and a sprite uses the pair or neither.</p>
    <div class="fills">%s</div>
  </div>
  <div>
    <div class="grp-h">Accent fills</div>
    <p class="small">Small internal areas only &mdash; under 40%% of a silhouette.</p>
    <div class="accs">%s</div>
    <div class="grp-h" style="margin-top:22px">Customer identity chips</div>
    <p class="small">Decorative identity only, never state. A customer whose chip is red must
    not read as urgent. All test &ge;&nbsp;4.5:1 against <code>ink-900</code> and carry
    <code>ink-950</code> initials. They belong to individual customers, never to us &mdash;
    a chip colour is not a brand colour.</p>
    <div class="chips">%s</div>
  </div>
</div>
""" % (fills, acc, chips))

# ---------------------------------------------------------------- 11 type
page("std", "11", "Typography", """
<div class="type-hero">
  <div class="tf">
    <div class="tf-spec bric">Caf&eacute; Rush</div>
    <div class="tf-m"><b>Bricolage Grotesque 800</b><span>Wordmark, headlines, screen titles,
    money totals, button labels, floating payments. 600 for subheads and standfirsts only,
    where 800 at that size would dominate the headline above it.</span></div>
  </div>
  <div class="tf">
    <div class="tf-spec dms">The dough takes five seconds</div>
    <div class="tf-m"><b>DM Sans 400 / 500 / 700</b><span>Running copy, hints, dish names,
    shop descriptions, settings, store descriptions, documents.</span></div>
  </div>
  <div class="tf">
    <div class="tf-spec dmm">AED 24.99 &nbsp; 0:90 &nbsp; &times;3</div>
    <div class="tf-m"><b>DM Mono 400 / 500</b><span>Clocks, timers, stock counts, prices, and
    every uppercase label style.</span></div>
  </div>
</div>
<div class="two even">
  <div>
    <div class="grp-h">Arabic</div>
    <p class="small"><b>Cairo 700 / 900</b> for the Arabic wordmark and all Arabic headlines,
    set at the same optical weight as Bricolage 800 and never lighter.
    <b>IBM Plex Sans Arabic 400 / 500 / 600</b> for all Arabic running copy and numerals, with
    <code>font-feature-settings: "tnum"</code>. Latin and Arabic lockups are built as two
    designs, not one flipped.</p>
  </div>
  <div>
    <div class="grp-h">Licensing</div>
    <p class="small">All five faces are SIL Open Font License, which is why they can ship
    inside the binary, inside a PDF and inside a web page without a per-seat count. The
    embedded set lives at <code>brand/fonts/fonts.css</code> &mdash; sixteen faces as data
    URIs, so a press kit renders correctly on a machine that has none of them installed.</p>
  </div>
</div>
""")

SCALE = [("display-xl", "Bricolage 800", "34 / 36", "Screen titles, the day's takings"),
         ("display-l", "Bricolage 800", "29 / 31", "Result headline"),
         ("display-m", "Bricolage 800", "22 / 24", "Card titles, dish price"),
         ("display-s", "Bricolage 800", "17 / 20", "Button labels"),
         ("body-l", "DM Sans 400", "15 / 22", "Running copy"),
         ("body-m", "DM Sans 400", "13 / 19", "Hints, descriptions"),
         ("body-s", "DM Sans 400", "11.5 / 17", "Dense list rows"),
         ("num-l", "DM Mono 500", "20 / 22", "Clock, cash total"),
         ("num-m", "DM Mono 500", "14 / 18", "Stock counts, timers"),
         ("num-s", "DM Mono 400", "11 / 14", "Inline counts"),
         ("label", "DM Mono 500", "9 / 12, +0.14em", "DAY, EARNED, TARGET, STREAK")]
page("std", "11", "Typography &mdash; the scale", """
<div class="two wide-left">
  <div>
    <div class="grp-h">The in-game scale is authoritative</div>
    <table class="scale">%s</table>
  </div>
  <div>
    <div class="grp-h">Above display-xl, multiply</div>
    <p class="small">Brand headlines continue the same ratio &mdash; 34, 48, 68, 96 &mdash;
    line-height 1.05 throughout, and nothing between those steps. Below <code>label</code>,
    nothing.</p>
    <div class="ladder">
      <div style="font-size:96px">96</div><div style="font-size:68px">68</div>
      <div style="font-size:48px">48</div><div style="font-size:34px">34</div>
    </div>
    <div class="callout neg">
      <div class="callout-h">The floor</div>
      <p>Minimum rendered size anywhere, in any medium, is 9&nbsp;pt, and only for
      <code>label</code>. Nothing a player must read while the clock runs is below 11&nbsp;pt.
      That applies to a banner and a slide exactly as it applies to a shift.</p>
    </div>
  </div>
</div>
""" % "".join('<tr><td><code>%s</code></td><td>%s</td><td class="num">%s</td><td class="use">%s</td></tr>'
              % r for r in SCALE))

HEADRULES = [
 "Bricolage 800, tracking &minus;0.02em at 22&nbsp;pt and above, &minus;0.01em from 17 to 21&nbsp;pt, 0 below. Never positive tracking in Bricolage.",
 "Maximum two lines. A headline that needs three is a headline that needs cutting.",
 "Ragged right, never justified, never centred over more than one line. Break lines on meaning, not on width.",
 "Sentence case always. The wordmark is Caf&eacute; Rush with the &eacute;, in both cases and at every size.",
 "Never all-caps, never letter-spaced, never outlined, never stretched, never gradiented, never shadowed. The one permitted effect is a <code>sun-300</code> glow behind the wordmark on key art, at 12% or less.",
 "<code>cream-50</code> on <code>ink-900</code>, or <code>ink-900</code> on <code>paper-100</code>. Amber headlines only when the headline is one word.",
 "Numerals inside a headline stay in Bricolage. Numerals that are data &mdash; a price, a clock, a count &mdash; switch to DM Mono, always. A price in a headline is data.",
 "Arabic headlines set in Cairo 900 at the same optical weight as Bricolage 800, never lighter.",
 "Minimum rendered size anywhere, in any medium: 9&nbsp;pt, and only for <code>label</code>.",
]
page("std", "11", "Typography &mdash; setting a headline", """
<div class="two even">
  <div>
    <div class="voice">%s</div>
  </div>
  <div>
    <div class="grp-h">Breaking on meaning</div>
    <div class="brk good"><span class="brk-t">Right</span>
      <div class="brk-h">A ninety-second cooking rush<br>you buy once and own forever.</div>
      <p>The break falls between the two claims. Each line is a complete thought.</p></div>
    <div class="brk bad"><span class="brk-t">Wrong</span>
      <div class="brk-h">A ninety-second cooking rush you buy<br>once and own forever.</div>
      <p>The break falls where the measure ran out. &ldquo;You buy&rdquo; dangles.</p></div>
  </div>
</div>
""" % "".join('<div class="vr"><span class="n">%d</span><div><span>%s</span></div></div>'
              % (i + 1, t) for i, t in enumerate(HEADRULES)))

# ---------------------------------------------------------------- 12 art
def strip(names, cls="s"):
    return "".join('<img class="%s" src="doc-assets/%s-128.png" alt="">' % (cls, n) for n in names)
page("std", "12", "Art direction", """
<div class="two wide-left art">
  <div>
    <div class="grp-h">Dishes &mdash; twelve</div><div class="sprites">%s</div>
    <div class="grp-h">Ingredients &mdash; eight</div><div class="sprites sm">%s</div>
    <div class="grp-h">Machines &mdash; six</div><div class="sprites sm">%s</div>
    <div class="grp-h">Customers &mdash; twelve, six shown</div><div class="sprites sm round">%s</div>
  </div>
  <div>
    <p class="lede">Forty-one assets: eight ingredients, twelve dishes, twelve customer
    portraits, six machines, three room plates. Glossy, appetising painted illustration with
    soft airbrushed shading and crisp specular highlights &mdash; warm and inviting, not
    photographic and not flat vector.</p>
    <p>They must look like one artist made all of them in one sitting. A single asset that is
    beautiful alone but sits at a different angle, scale or light direction ruins the set, so
    consistency outranks any individual image. Light falls from the upper left throughout.</p>
    <p>Each is cut from its backdrop by a flood fill inward from the edges rather than a
    colour threshold, so an object&rsquo;s own mid-greys survive. Portraits are cropped to the
    head &mdash; a bust at 40&nbsp;px leaves a 16&nbsp;px face &mdash; and faded rather than
    cut, so the crop reads as a vignette.</p>
    <div class="callout neg">
      <div class="callout-h">Marketing art is the shipped art</div>
      <p>Every dish, machine, portrait and room in a banner or press image is a file from
      <code>art/sprites/</code>, at or below its rendered size in the build. No stock
      photography, no separately commissioned key art, nothing drawn at a fidelity the game
      does not contain. <code>ink-outline</code> is the only stroke colour anywhere.</p>
    </div>
  </div>
</div>
""" % (strip(DISHES), strip(ING), strip(MACH), strip(PORT)))

page("std", "12", "Art direction &mdash; the room", """
<div class="rooms">
  <div><img src="doc-assets/room_day-560.jpg" alt=""><span>room_day &mdash; the shift</span></div>
  <div><img src="doc-assets/room_evening-560.jpg" alt=""><span>room_evening &mdash; results, menus, key art</span></div>
  <div><img src="doc-assets/room_counter-560.jpg" alt=""><span>room_counter &mdash; the working band</span></div>
</div>
<p class="foot-note">Three plates, one room, three times of day. A plate is always pushed
back behind the interface &mdash; darkened, slightly desaturated, and never competing with a
sprite the player must read. In marketing it carries a scrim at 55&ndash;97% so type sits on
<code>ink-900</code>, not on a photograph.</p>
""")

# ---------------------------------------------------------------- 13 marketing
page("std", "13", "Marketing", """
<div class="mk">
  <div><img src="doc-assets/mk-feature-1024.jpg" alt="">
    <span>Google Play feature graphic &middot; 1024 &times; 500</span></div>
  <div><img src="doc-assets/mk-social-1200.jpg" alt="">
    <span>Social and Open Graph banner &middot; 1200 &times; 630</span></div>
</div>
<div class="four tight">
  <div><div class="k">The structure</div><p>Copy left, food right, always. Type never sits
  over a sprite and a sprite never sits over type.</p></div>
  <div><div class="k">The ground</div><p>A room plate at 62% brightness under an
  <code>ink-900</code> scrim, plus a <code>sun-300</code> glow at 12% behind the mark.</p></div>
  <div><div class="k">The copy</div><p>Wordmark, the promise broken on meaning, a 52&nbsp;px
  amber rule, then the subtitle as a mono label. Nothing else.</p></div>
  <div><div class="k">The one accent</div><p><code>amber-500</code> appears twice: the
  &eacute; and the rule. One cool note per composition is permitted; two is not.</p></div>
</div>
""")

# ---------------------------------------------------------------- 14 store
page("std", "14", "Store listing &mdash; Apple", """
<div class="two even">
  <div>
    <div class="strings">
      <div class="str"><span class="str-l">Title &mdash; 23 of 30</span><code>Caf&eacute; Rush: Cooking Game</code></div>
      <div class="str"><span class="str-l">Subtitle &mdash; 29 of 30</span><code>No ads. No timers. One price.</code></div>
    </div>
    <div class="grp-h">Promotional text &mdash; 165 of 170</div>
    <div class="copyblock">The first chapter is free. If the ninety seconds grab you, one
    payment of AED 24.99 opens the other twenty-four days. No ads, no gems, no energy, no
    second purchase.</div>
    <div class="grp-h">Keyword field &mdash; 93 of 100</div>
    <div class="copyblock mono">diner,restaurant,chef,time management,karak,offline,premium,tycoon,dash,uae,arabic,food,serve</div>
    <p class="small">Cooking, caf&eacute;, rush, ads, timers and price are deliberately absent
    &mdash; Apple indexes the title and subtitle already, and repeating them wastes the
    hundred characters.</p>
  </div>
  <div>
    <div class="grp-h">Description &mdash; opening</div>
    <div class="copyblock">Ninety seconds. Five seats filling at once. The dough takes five of
    those seconds, which means you start it before anyone has ordered it &mdash; and that is
    the whole game. Machines cook ingredients on their own timers into bins behind you; dishes
    are assembled from that stock in an instant. Being fast is not the skill. Holding the right
    thing before it is asked for is the skill.</div>
    <div class="callout">
      <div class="callout-h">Why the opening paragraph is a mechanic, not a mood</div>
      <p>The scanning player has read a thousand openings that promise excitement. She has
      never read one that told her the dough takes five seconds. Specificity is how a small
      game sounds confident next to a big one, and it is the only opening that a competitor
      with a bigger budget cannot copy without changing their game.</p>
    </div>
  </div>
</div>
""")

page("std", "14", "Store listing &mdash; the description", """
<div class="desc">
  <p>You run a small caf&eacute; on a shopping street in the UAE. Karak chai, luqaimat, regag
  rolls, saffron karak, and nine more recipes across thirty days. Customers sit down, order up
  to three things, and lose patience at their own pace. The counter holds only a few plates and
  a full counter blocks you, so starting the wrong machine is a mistake, not a delay.</p>
  <p>Thirty days in five chapters. Each chapter adds something the last one could not do:
  regulars with a usual order, food that goes cold, customers who change their mind, a machine
  that breaks mid-shift. Day nineteen is not day four with a faster clock.</p>
  <p>Then Endless Rush, which does not end. One continuous shift that steps up every
  twenty-five seconds until three customers walk out. Your own best run is the only score that
  matters.</p>
  <p>The first chapter is free &mdash; six days, six recipes, about half an hour, with a proper
  ending rather than a locked door. If you want the rest, it is one payment of AED 24.99.</p>
  <p class="em">That is the only purchase in this game.</p>
  <p>No ads of any kind. No energy meter. No premium currency. No daily rewards, no login
  streaks, no limited-time events, nothing that expires. Nothing you can buy makes a shift
  easier. No friends required, no account, no internet &mdash; it plays in aeroplane mode
  forever. Put it down for a month and it is exactly where you left it.</p>
  <p>Relaxed Timing is free and earns full stars. Three colour-blind palettes, high contrast,
  larger text, reduced motion, left-handed layout. In-shift screen-reader play is not supported
  in this version, and we would rather say so than claim it.</p>
  <p>English and Arabic, both fully laid out right-to-left where they should be.</p>
</div>
<p class="foot-note">Seven paragraphs, none longer than four sentences, no exclamation mark,
no adjective doing sales work, and one stated limitation. The limitation is not an oversight
&mdash; a listing that omits it to look cleaner has broken rule&nbsp;9.</p>
""")

# ---------------------------------------------------------------- 15 rules
RULES_C = [
 "There is never a second thing for sale. One non-consumable at AED 24.99, forever. Paid expansions, if they ever ship, are self-contained, separately titled, and never required to finish what a player already owns.",
 "No ad SDK is ever linked into the binary, including for attribution or analytics.",
 "No premium currency, no consumable, no boost, no subscription, no season, no battle pass.",
 "Nothing purchasable ever makes a shift easier, and nothing that makes a shift easier is ever purchasable.",
 "No discount countdown, no launch-week urgency, no &ldquo;price rises soon&rdquo;. A price change is announced plainly and without a deadline.",
 "No daily reward, streak, event, or expiring content of any kind. If it can be earned today, it can be earned in six months, identically.",
 "No notification that asks a player to come back. Notifications are off by default and only ever a reminder the player set themselves.",
 "No leaderboard, invite, share-to-continue, account requirement or online dependency.",
 "The store listing never states a claim the binary does not honour, and never omits a limitation to make the listing cleaner.",
]
RULES_V = [
 "No exclamation marks in player-facing strings. None.",
 "The banned words are banned in every channel: amazing, epic, ultimate, addictive, insane, crazy, satisfying, relaxing, stunning, unlock the fun, get ready.",
 "The game is never described as cozy, casual, relaxing or calm. It is a rush.",
 "No invented number ever appears &mdash; no download counts, no ratings we have not received, no market statistics, no &ldquo;loved by thousands&rdquo;.",
 "Failure copy never scolds, consoles or apologises. It says what happened.",
 "Local dish names are never glossed twice, never italicised, never framed as exotic.",
 "The Arabic build is never shipped late, never machine-translated, and never shown with English screenshots.",
]
RULES_VIS = [
 "A hex value that is not a <code>docs/design-spec.md</code> &sect;2.3 token &mdash; or <code>terracotta-400</code> / <code>paper-100</code> &mdash; never appears in any asset, in the game or out of it.",
 "<code>brass-400</code> is money and nothing else. <code>ok-500</code> is money earned and target met and nothing else. <code>state-urgent</code> never touches food, a resting button or a marketing field.",
 "<code>ink-outline</code> <code>#2A1D16</code> is the only stroke colour on any artwork anywhere.",
 "The wordmark is Bricolage Grotesque 800, sentence case, with the &eacute;. Never all-caps, letter-spaced, outlined, stretched, gradiented or shadowed, and never on a ground other than <code>ink-900</code>, <code>ink-950</code> or <code>paper-100</code>.",
 "Headlines are never longer than two lines and never centred over more than one.",
 "No screenshot is ever mocked up, upscaled, composited from art we do not ship, or taken from a build with features the store version does not have. What is on the store page is what installs.",
 "Marketing art is the shipped art &mdash; a file from <code>art/sprites/</code>, at or below its rendered size in the build. No stock photography, no photographic food, no separately commissioned key art, nothing drawn at a fidelity the game does not contain.",
 "Nothing flashes more than three times a second, in the game or in a trailer.",
 "Nothing ever renders below 9&nbsp;pt, and nothing below 11&nbsp;pt that a player must read while the clock runs.",
]
def rule_list(rows, start):
    return "".join('<div class="vr"><span class="n">%d</span><div><span>%s</span></div></div>'
                   % (start + i, t) for i, t in enumerate(rows))
page("std", "15", "The rules &mdash; commercial", """
<p class="lede">The list that holds when someone is in a hurry. Every line is a veto, not a
preference. These nine are contractual rather than stylistic: breaking one is not a
design mistake, it is a breach of the deal the player paid into.</p>
<div class="voice cols2">%s</div>
""" % rule_list(RULES_C, 1))
page("std", "15", "The rules &mdash; verbal and visual", """
<div class="two even">
  <div><div class="grp-h">Verbal</div><div class="voice">%s</div></div>
  <div><div class="grp-h">Visual</div><div class="voice">%s</div></div>
</div>
""" % (rule_list(RULES_V, 10), rule_list(RULES_VIS, 17)))

# ---------------------------------------------------------------- 16 index
page("std", "16", "What ships in this kit", """
<div class="two even">
  <div>
    <div class="grp-h">Files</div>
    <table class="idx">
      <tr><td><code>brand/guidelines.pdf</code></td><td>This document, 28 pages, fonts embedded</td></tr>
      <tr><td><code>brand/strategy.md</code></td><td>The long-form strategy these pages compress</td></tr>
      <tr><td><code>brand/fonts/fonts.css</code></td><td>16 faces as data URIs. Drop-in for a press page</td></tr>
      <tr><td><code>assets/colour/tokens.css</code></td><td>30 core tokens, 6 art fills, 8 accent fills</td></tr>
      <tr><td><code>assets/colour/tokens.json</code></td><td>The same, with contrast ratios and never-rules</td></tr>
      <tr><td><code>assets/colour/swatches-*.png</code></td><td>Six swatch sheets, one per group</td></tr>
      <tr><td><code>assets/logo/</code></td><td>7 wordmark and lockup variants, dark, light and mono</td></tr>
      <tr><td><code>assets/icon/ios/</code></td><td>18 sizes, 29 to 1024, from one master</td></tr>
      <tr><td><code>assets/icon/android/</code></td><td>10 files including the adaptive pair and Play 512</td></tr>
      <tr><td><code>assets/icon/web/</code></td><td>5 favicon and web-manifest sizes</td></tr>
      <tr><td><code>assets/marketing/</code></td><td>Play feature graphic, social and OG banner</td></tr>
      <tr><td><code>art/sprites/</code></td><td>41 game assets at 512, plus @34 and @20 game sizes</td></tr>
    </table>
  </div>
  <div>
    <div class="grp-h">Regenerating</div>
    <p class="small">Nothing in this kit is edited by hand. <code>build-tokens.py</code> writes
    the stylesheet, the JSON and the swatch source from one table.
    <code>build-guidelines.py</code> writes this document from that JSON plus the strategy
    copy. <code>render-guidelines.js</code> drives headless Chromium to produce the PDF and the
    swatch sheets. Change the table, run the three, and the book, the stylesheet and the
    swatches move together.</p>
    <div class="callout">
      <div class="callout-h">What is not here yet</div>
      <p>Store screenshots, which must be taken from a real build rather than mocked up, and
      the trailer. Both are blocked on the same thing: rule&nbsp;22 means we cannot make them
      until the build shows what they would show.</p>
    </div>
    <div class="endmark">
      <div class="wm" style="font-size:44px">Caf<i>&eacute;</i> Rush</div>
      <p>A ninety-second cooking rush you buy once and own forever.</p>
    </div>
  </div>
</div>
""")

# ================================================================= assemble
CSS = (ROOT / "guidelines.css").read_text()
body = []
n = 0
for kind, sec, title, content, dark in pages:
    n += 1
    cls = "page" + (" cover" if kind == "cover" else "") + (" dark" if dark else "")
    if kind == "cover":
        body.append('<section class="%s">%s</section>' % (cls, content))
    else:
        body.append(
          '<section class="%s"><header class="ph">'
          '<div class="ph-l"><span class="ph-n">%s</span>%s</div>'
          '<div class="ph-r">Caf&eacute; Rush &mdash; brand guidelines</div></header>'
          '<div class="pb">%s</div>'
          '<footer class="pf"><span>Version 1.0 &middot; 16 September 2026</span>'
          '<span class="pg">%02d</span></footer></section>' % (cls, sec, title, content, n))

doc = """<!doctype html><html lang="en-GB"><head><meta charset="utf-8">
<title>Caf&eacute; Rush &mdash; brand guidelines</title>
<link rel="stylesheet" href="fonts/fonts.css">
<link rel="stylesheet" href="assets/colour/tokens.css">
<style>%s</style></head><body>%s</body></html>""" % (CSS, "\n".join(body))
(ROOT / "guidelines.html").write_text(doc)
print("guidelines.html: %d pages" % n)
