/**
 * Draws the brand marks into src/ui/marks.ts as data URIs.
 *
 *   node scripts/generate-marks.js
 *
 * Both are white silhouettes on transparency, so the app tints them to
 * whatever the screen needs rather than shipping one image per colour. The
 * flame in the emblem is a hole rather than a fill, which is why the mark
 * works on paper, on a card back and on a coral button without being redrawn.
 */

const fs = require('fs');
const path = require('path');

const { dataUri } = require('./png.js');
const { coverage, placed, roundedBox, FLAME } = require('./shapes.js');

/**
 * Each mark is drawn to a canvas cut to its own shape rather than to a square.
 * A square would leave the app fitting a letter-shaped card inside a box and
 * shrinking it to nothing in the process.
 */
function render(width, height, predicate) {
  const pixels = Buffer.alloc(width * height * 4);
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const alpha = coverage(predicate, x, y);
      const at = (y * width + x) * 4;
      pixels[at] = 255;
      pixels[at + 1] = 255;
      pixels[at + 2] = 255;
      pixels[at + 3] = Math.round(alpha * 255);
    }
  }
  return dataUri(width, height, pixels);
}

const FIRE = 256;
const flame = render(FIRE, FIRE, placed(FLAME, FIRE / 2, FIRE / 2, FIRE * 0.96));

/* The card, upright: in the wordmark it stands in for a letter, and letters
 * do not lean. Its canvas is the card's own bounding box plus a hair. */
const S = 340;
const CARD_W = Math.round(S * 0.56) + 2;
const CARD_H = Math.round(S * 0.76) + 2;
const card = roundedBox(CARD_W / 2, CARD_H / 2, S * 0.28, S * 0.38, S * 0.065, 0);
const fire = placed(FLAME, CARD_W / 2, CARD_H / 2, S * 0.52, 0);
const mark = render(CARD_W, CARD_H, (x, y) => card(x, y) && !fire(x, y));

const file = `/**
 * Generated by scripts/generate-marks.js — do not edit by hand.
 *
 * The two brand shapes, as white silhouettes on transparency. Tint them at
 * the point of use; the flame inside the emblem is a hole, so whatever is
 * behind the mark shows through it.
 */

export const FLAME_GLYPH = '${flame}';

export const EMBLEM = '${mark}';

/** The card's shape, so a caller can size it by height and get the width right. */
export const EMBLEM_ASPECT = ${(CARD_W / CARD_H).toFixed(4)};
`;

const out = path.join(__dirname, '..', 'src', 'ui', 'marks.ts');
fs.writeFileSync(out, file);
console.log(`wrote src/ui/marks.ts — ${Math.round(file.length / 1024)} KB`);
