// Per-arena forward drive.
//
// GENERATED by tools/calibrate.mjs -- run that, do not edit DRIVE by hand.
//
// Drive is the single knob that sets how hard each marble pushes toward the end
// it is attacking, and it is monotone in goals-per-match, so one binary search
// per arena is enough to land all twenty-five on their target scoring rates.
//
// Nothing here is per-nation. Drive is a property of the arena and applies
// identically to both marbles.

export const DRIVE = {
  rotor: 23.4,
  pinball: 23.4,
  channels: 19.1,
  slalom: 2.1,
  forest: 3.6,
  bounce: 2.5,
  carousel: 3.6,
  tide: 35.5,
  crumble: 12.3,
  crossfire: 13.8,
  hourglass: 2.1,
  shutters: 35.5,
  conveyor: 4.4,
  catapult: 68.2,
  split: 3.8,
  spiral: 18.6,
  iris: 4.2,
  twinrings: 1.3,
  pendulum: 25.9,
  minefield: 9.5,
  wells: 1.5,
  drum: 3.2,
  magnets: 3.4,
  bowl: 10.4,
  grand: 20.4,
};

// Goals per match each arena aims for. Variety is deliberate: a cagey 2.0-goal
// final and a 3.0-goal shoot-out are both football.
export const TARGETS = {
  rotor: 2.3,
  pinball: 2.9,
  channels: 2.8,
  slalom: 2.6,
  forest: 2.5,
  bounce: 2.8,
  carousel: 2.7,
  tide: 2.3,
  crumble: 2.9,
  crossfire: 2.6,
  hourglass: 2.4,
  shutters: 2.6,
  conveyor: 2.8,
  catapult: 3,
  split: 2.6,
  spiral: 2.5,
  iris: 2.4,
  twinrings: 2.3,
  pendulum: 2.2,
  minefield: 2.8,
  wells: 2.7,
  drum: 2.1,
  magnets: 2.9,
  bowl: 2.2,
  grand: 2,
};
