#!/usr/bin/env python3
"""Bundle the game into one offline HTML string for the Expo WebView.

A WebView given `source={{ html }}` has no origin and cannot fetch siblings, so everything
has to live in the one string. That is the same constraint marble-ultimate-football solves in
native/scripts/build-webapp.mjs, and this is the same answer.

The difference is the art. That game is vector and CSS and bundles to 1.26MB; Café Life is
140 sprites and 7.5MB of PNG, which base64 encodes to 10MB in a single JavaScript module.
WebP takes the same images to 2.1MB -- 2.8MB encoded -- at a quality that does not read as
lossy against the originals, so the whole game still fits in one string. WebP has been
supported in WKWebView since iOS 14 and the app targets iOS 15.

Generated, never edited. prototype/cafelife.html stays the only copy of the game.
"""
import base64, io, os, re, json
from PIL import Image

# Anchored to the repository, not to the shell's working directory. npm runs a script from the
# directory of its package.json, so `npm run webapp` -- which is what `npm run build:testflight`
# and `npm run ios` both start with -- invoked this from native/ and it died on a relative
# "art/sprites" that only resolved when run by hand from the root.
ROOT  = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC   = os.path.join(ROOT, "art/sprites")
GAME  = os.path.join(ROOT, "prototype/cafelife.html")
OUT   = os.path.join(ROOT, "native/src/webapp/html.js")
SQ, WIDE = 128, 900
Q_SQ, Q_WIDE = 82, 74


def encode(path):
    """One sprite, at the size the game draws it, as a data URI."""
    im = Image.open(path)
    wide = im.width != im.height
    if wide:
        im = im.convert("RGB").resize((WIDE, round(im.height * WIDE / im.width)), Image.LANCZOS)
    else:
        im = im.convert("RGBA").resize((SQ, SQ), Image.LANCZOS)
    buf = io.BytesIO()
    im.save(buf, "WEBP", quality=Q_WIDE if wide else Q_SQ, method=6)
    return "data:image/webp;base64," + base64.b64encode(buf.getvalue()).decode()


def main():
    art = {}
    for f in sorted(os.listdir(SRC)):
        if f.endswith(".png") and "@" not in f:
            art[f[:-4]] = encode(os.path.join(SRC, f))

    html = open(GAME, encoding="utf-8").read()

    # Every sprite URL in the game is built as `ART + <something> + ".png"`. With no origin
    # there is nothing to resolve a path against, so each one becomes a lookup instead.
    html, n = re.subn(r'ART \+ (.+?) \+ "\.png"', r'art(\1)', html)
    assert n == 5, "expected 5 sprite URLs, found %d -- did cafelife.html change?" % n
    html = html.replace('const ART = "../art/sprites/";',
                        'const art = n => (ART_DATA[n] || "");')
    assert "ART_DATA" in html, "the ART constant was not replaced"

    head, body = html.split("</head><body>", 1)
    head = re.sub(r"^<!doctype html><html[^>]*><head>", "", head, flags=re.I)
    head = re.sub(r"<meta[^>]*>", "", head, flags=re.I)
    body = body.rsplit("</body></html>", 1)[0]

    # The Google Fonts link cannot survive: in aeroplane mode it silently falls back to the
    # system face, which is the one situation nobody tests. The faces are bundled instead.
    fonts = open(os.path.join(ROOT, "native/assets/fonts/fonts.css"), encoding="utf-8").read()
    head, nlink = re.subn(r'<link rel="stylesheet" href="https://fonts\.googleapis\.com[^>]*>',
                          "", head)
    assert nlink == 1, "expected one Google Fonts link, found %d" % nlink

    doc = ('<!doctype html><html lang="en"><head><meta charset="utf-8">'
           '<meta name="viewport" content="width=device-width,initial-scale=1,'
           'maximum-scale=1,user-scalable=no,viewport-fit=cover">'
           '<style>html,body{background:#171310;-webkit-user-select:none;user-select:none;'
           '-webkit-touch-callout:none;overscroll-behavior:none}'
           ':root{padding-top:env(safe-area-inset-top,0px);'
           'padding-bottom:env(safe-area-inset-bottom,0px)}</style>'
           + "<style>" + fonts + "</style>"
           + head.strip()
           + "<script>const ART_DATA=" + json.dumps(art, separators=(",", ":")) + ";</script>"
           + '</head><body>' + body.strip() + '</body></html>')

    # The whole point of the string is that it needs nothing. Prove it rather than hope.
    outbound = re.findall(r'(?:src|href)=["\'](https?://[^"\']+)', doc)
    assert not outbound, "the bundle would fetch at runtime: %s" % outbound[:3]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("// Generated by tools/build-native.py. Do not edit.\n"
                 "// The whole game, offline, in one string: %d sprites as WebP data URIs.\n"
                 "export const HTML = %s;\n" % (len(art), json.dumps(doc)))
    print("%d sprites embedded -> %s, %.2f MB"
          % (len(art), os.path.relpath(OUT, ROOT), os.path.getsize(OUT) / 1e6))


main()
