/**
 * The sounds of the table.
 *
 * Every effect is generated by scripts/generate-sounds.js — nothing is
 * sampled, nothing is licensed, and changing how a burn sounds is a one-line
 * edit in that file. Audio is a nicety, so everything here fails quietly: a
 * device that will not play a sound still plays the game.
 */

import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';

export type Cue =
  | 'deal'
  | 'draw'
  | 'throw'
  | 'land'
  | 'burn'
  | 'knock'
  | 'alert'
  | 'flip'
  | 'chime';

const SOURCES: Record<Cue, number> = {
  deal: require('../../assets/sfx/deal.wav'),
  draw: require('../../assets/sfx/draw.wav'),
  throw: require('../../assets/sfx/throw.wav'),
  land: require('../../assets/sfx/land.wav'),
  burn: require('../../assets/sfx/burn.wav'),
  knock: require('../../assets/sfx/knock.wav'),
  alert: require('../../assets/sfx/alert.wav'),
  flip: require('../../assets/sfx/flip.wav'),
  chime: require('../../assets/sfx/chime.wav'),
};

/** Balance, set by ear rather than by meter. */
const LEVEL: Record<Cue, number> = {
  deal: 0.45,
  draw: 0.4,
  throw: 0.5,
  land: 0.45,
  burn: 0.6,
  knock: 0.65,
  alert: 0.6,
  flip: 0.3,
  chime: 0.5,
};

const players = new Map<Cue, AudioPlayer>();
let enabled = true;
let started = false;

/**
 * Loads the effects. Called once the player has actually started a game, which
 * on the web also means a tap has happened and the browser will let us make a
 * noise at all.
 */
export function primeSound(): void {
  if (started) return;
  started = true;
  try {
    // Sound effects should duck under nothing and never stop anyone's music.
    void setAudioModeAsync({
      playsInSilentMode: false,
      shouldPlayInBackground: false,
      interruptionMode: 'mixWithOthers',
    }).catch(() => undefined);
  } catch {
    // An older runtime without audio modes still plays sounds.
  }

  for (const cue of Object.keys(SOURCES) as Cue[]) {
    try {
      const player = createAudioPlayer(SOURCES[cue]);
      player.volume = LEVEL[cue];
      players.set(cue, player);
    } catch {
      // One sound failing to load must not take the rest with it.
    }
  }
}

export function setSoundEnabled(on: boolean): void {
  enabled = on;
}

export function isSoundEnabled(): boolean {
  return enabled;
}

/** Plays a cue from the start, cutting off its previous run if it is still going. */
export function play(cue: Cue): void {
  if (!enabled) return;
  const player = players.get(cue);
  if (!player) return;
  try {
    void player.seekTo(0)?.catch?.(() => undefined);
    player.play();
  } catch {
    // A sound that will not play is not worth interrupting a game over.
  }
}

/** Releases the players. Called when the app is done with the table. */
export function releaseSound(): void {
  for (const player of players.values()) {
    try {
      player.remove();
    } catch {
      // Already gone.
    }
  }
  players.clear();
  started = false;
}
